// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shop.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Shop struct {
	ImagePath            string   `protobuf:"bytes,1,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude             float32  `protobuf:"fixed32,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Introduction         string   `protobuf:"bytes,5,opt,name=introduction,proto3" json:"introduction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shop) Reset()         { *m = Shop{} }
func (m *Shop) String() string { return proto.CompactTextString(m) }
func (*Shop) ProtoMessage()    {}
func (*Shop) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{0}
}

func (m *Shop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shop.Unmarshal(m, b)
}
func (m *Shop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shop.Marshal(b, m, deterministic)
}
func (m *Shop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shop.Merge(m, src)
}
func (m *Shop) XXX_Size() int {
	return xxx_messageInfo_Shop.Size(m)
}
func (m *Shop) XXX_DiscardUnknown() {
	xxx_messageInfo_Shop.DiscardUnknown(m)
}

var xxx_messageInfo_Shop proto.InternalMessageInfo

func (m *Shop) GetImagePath() string {
	if m != nil {
		return m.ImagePath
	}
	return ""
}

func (m *Shop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Shop) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Shop) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Shop) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

type GetShopRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShopRequest) Reset()         { *m = GetShopRequest{} }
func (m *GetShopRequest) String() string { return proto.CompactTextString(m) }
func (*GetShopRequest) ProtoMessage()    {}
func (*GetShopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{1}
}

func (m *GetShopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShopRequest.Unmarshal(m, b)
}
func (m *GetShopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShopRequest.Marshal(b, m, deterministic)
}
func (m *GetShopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShopRequest.Merge(m, src)
}
func (m *GetShopRequest) XXX_Size() int {
	return xxx_messageInfo_GetShopRequest.Size(m)
}
func (m *GetShopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShopRequest proto.InternalMessageInfo

func (m *GetShopRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetShopResponse struct {
	Shops                []*Shop  `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShopResponse) Reset()         { *m = GetShopResponse{} }
func (m *GetShopResponse) String() string { return proto.CompactTextString(m) }
func (*GetShopResponse) ProtoMessage()    {}
func (*GetShopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{2}
}

func (m *GetShopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShopResponse.Unmarshal(m, b)
}
func (m *GetShopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShopResponse.Marshal(b, m, deterministic)
}
func (m *GetShopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShopResponse.Merge(m, src)
}
func (m *GetShopResponse) XXX_Size() int {
	return xxx_messageInfo_GetShopResponse.Size(m)
}
func (m *GetShopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetShopResponse proto.InternalMessageInfo

func (m *GetShopResponse) GetShops() []*Shop {
	if m != nil {
		return m.Shops
	}
	return nil
}

type PostShopRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostShopRequest) Reset()         { *m = PostShopRequest{} }
func (m *PostShopRequest) String() string { return proto.CompactTextString(m) }
func (*PostShopRequest) ProtoMessage()    {}
func (*PostShopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{3}
}

func (m *PostShopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostShopRequest.Unmarshal(m, b)
}
func (m *PostShopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostShopRequest.Marshal(b, m, deterministic)
}
func (m *PostShopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostShopRequest.Merge(m, src)
}
func (m *PostShopRequest) XXX_Size() int {
	return xxx_messageInfo_PostShopRequest.Size(m)
}
func (m *PostShopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostShopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostShopRequest proto.InternalMessageInfo

func (m *PostShopRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type PostShopResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostShopResponse) Reset()         { *m = PostShopResponse{} }
func (m *PostShopResponse) String() string { return proto.CompactTextString(m) }
func (*PostShopResponse) ProtoMessage()    {}
func (*PostShopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{4}
}

func (m *PostShopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostShopResponse.Unmarshal(m, b)
}
func (m *PostShopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostShopResponse.Marshal(b, m, deterministic)
}
func (m *PostShopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostShopResponse.Merge(m, src)
}
func (m *PostShopResponse) XXX_Size() int {
	return xxx_messageInfo_PostShopResponse.Size(m)
}
func (m *PostShopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostShopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostShopResponse proto.InternalMessageInfo

func (m *PostShopResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type PutShopRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutShopRequest) Reset()         { *m = PutShopRequest{} }
func (m *PutShopRequest) String() string { return proto.CompactTextString(m) }
func (*PutShopRequest) ProtoMessage()    {}
func (*PutShopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{5}
}

func (m *PutShopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutShopRequest.Unmarshal(m, b)
}
func (m *PutShopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutShopRequest.Marshal(b, m, deterministic)
}
func (m *PutShopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutShopRequest.Merge(m, src)
}
func (m *PutShopRequest) XXX_Size() int {
	return xxx_messageInfo_PutShopRequest.Size(m)
}
func (m *PutShopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutShopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutShopRequest proto.InternalMessageInfo

func (m *PutShopRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type PutShopResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutShopResponse) Reset()         { *m = PutShopResponse{} }
func (m *PutShopResponse) String() string { return proto.CompactTextString(m) }
func (*PutShopResponse) ProtoMessage()    {}
func (*PutShopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{6}
}

func (m *PutShopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutShopResponse.Unmarshal(m, b)
}
func (m *PutShopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutShopResponse.Marshal(b, m, deterministic)
}
func (m *PutShopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutShopResponse.Merge(m, src)
}
func (m *PutShopResponse) XXX_Size() int {
	return xxx_messageInfo_PutShopResponse.Size(m)
}
func (m *PutShopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutShopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutShopResponse proto.InternalMessageInfo

func (m *PutShopResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type DeleteShopRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShopRequest) Reset()         { *m = DeleteShopRequest{} }
func (m *DeleteShopRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShopRequest) ProtoMessage()    {}
func (*DeleteShopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{7}
}

func (m *DeleteShopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShopRequest.Unmarshal(m, b)
}
func (m *DeleteShopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShopRequest.Marshal(b, m, deterministic)
}
func (m *DeleteShopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShopRequest.Merge(m, src)
}
func (m *DeleteShopRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShopRequest.Size(m)
}
func (m *DeleteShopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShopRequest proto.InternalMessageInfo

func (m *DeleteShopRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DeleteShopResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShopResponse) Reset()         { *m = DeleteShopResponse{} }
func (m *DeleteShopResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteShopResponse) ProtoMessage()    {}
func (*DeleteShopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{8}
}

func (m *DeleteShopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShopResponse.Unmarshal(m, b)
}
func (m *DeleteShopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShopResponse.Marshal(b, m, deterministic)
}
func (m *DeleteShopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShopResponse.Merge(m, src)
}
func (m *DeleteShopResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteShopResponse.Size(m)
}
func (m *DeleteShopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShopResponse proto.InternalMessageInfo

func (m *DeleteShopResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ShopImage struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopImage) Reset()         { *m = ShopImage{} }
func (m *ShopImage) String() string { return proto.CompactTextString(m) }
func (*ShopImage) ProtoMessage()    {}
func (*ShopImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{9}
}

func (m *ShopImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopImage.Unmarshal(m, b)
}
func (m *ShopImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopImage.Marshal(b, m, deterministic)
}
func (m *ShopImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopImage.Merge(m, src)
}
func (m *ShopImage) XXX_Size() int {
	return xxx_messageInfo_ShopImage.Size(m)
}
func (m *ShopImage) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopImage.DiscardUnknown(m)
}

var xxx_messageInfo_ShopImage proto.InternalMessageInfo

func (m *ShopImage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadShopImageResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadShopImageResponse) Reset()         { *m = UploadShopImageResponse{} }
func (m *UploadShopImageResponse) String() string { return proto.CompactTextString(m) }
func (*UploadShopImageResponse) ProtoMessage()    {}
func (*UploadShopImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{10}
}

func (m *UploadShopImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadShopImageResponse.Unmarshal(m, b)
}
func (m *UploadShopImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadShopImageResponse.Marshal(b, m, deterministic)
}
func (m *UploadShopImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadShopImageResponse.Merge(m, src)
}
func (m *UploadShopImageResponse) XXX_Size() int {
	return xxx_messageInfo_UploadShopImageResponse.Size(m)
}
func (m *UploadShopImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadShopImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadShopImageResponse proto.InternalMessageInfo

func (m *UploadShopImageResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Shop)(nil), "protocol.Shop")
	proto.RegisterType((*GetShopRequest)(nil), "protocol.GetShopRequest")
	proto.RegisterType((*GetShopResponse)(nil), "protocol.GetShopResponse")
	proto.RegisterType((*PostShopRequest)(nil), "protocol.PostShopRequest")
	proto.RegisterType((*PostShopResponse)(nil), "protocol.PostShopResponse")
	proto.RegisterType((*PutShopRequest)(nil), "protocol.PutShopRequest")
	proto.RegisterType((*PutShopResponse)(nil), "protocol.PutShopResponse")
	proto.RegisterType((*DeleteShopRequest)(nil), "protocol.DeleteShopRequest")
	proto.RegisterType((*DeleteShopResponse)(nil), "protocol.DeleteShopResponse")
	proto.RegisterType((*ShopImage)(nil), "protocol.ShopImage")
	proto.RegisterType((*UploadShopImageResponse)(nil), "protocol.UploadShopImageResponse")
}

func init() { proto.RegisterFile("shop.proto", fileDescriptor_0f3030369b20fd61) }

var fileDescriptor_0f3030369b20fd61 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0xae, 0x93, 0x40,
	0x14, 0x86, 0x4b, 0x81, 0xa6, 0x9c, 0x36, 0xad, 0x1e, 0x8d, 0x22, 0xd6, 0x58, 0x27, 0x46, 0xa9,
	0x31, 0x4d, 0xac, 0x0b, 0x37, 0x4d, 0xdc, 0x68, 0x9a, 0xee, 0x08, 0xc6, 0xb5, 0x19, 0xcb, 0xa4,
	0x10, 0x29, 0x83, 0x9d, 0xe1, 0x59, 0xee, 0x9b, 0xdd, 0xe7, 0xb9, 0x99, 0x81, 0x0b, 0xa5, 0xb7,
	0x37, 0x74, 0xc5, 0xcc, 0xf9, 0xbf, 0xfc, 0xe7, 0xcc, 0xf9, 0x01, 0x10, 0x31, 0xcf, 0x97, 0xf9,
	0x91, 0x4b, 0x8e, 0x43, 0xfd, 0xd9, 0xf1, 0x94, 0xdc, 0x18, 0x60, 0xfd, 0x8a, 0x79, 0x8e, 0x6f,
	0x00, 0x92, 0x03, 0xdd, 0xb3, 0x3f, 0x39, 0x95, 0xb1, 0x6b, 0xcc, 0x0d, 0xdf, 0x09, 0x1d, 0x5d,
	0x09, 0xa8, 0x8c, 0x11, 0xc1, 0xca, 0xe8, 0x81, 0xb9, 0x7d, 0x2d, 0xe8, 0x33, 0x7a, 0x30, 0x4c,
	0xa9, 0x4c, 0x64, 0x11, 0x31, 0xd7, 0x9c, 0x1b, 0x7e, 0x3f, 0xac, 0xef, 0x38, 0x03, 0x27, 0xe5,
	0xd9, 0xbe, 0x14, 0x2d, 0x2d, 0x36, 0x05, 0x24, 0x30, 0x4e, 0x32, 0x79, 0xe4, 0x51, 0xb1, 0x93,
	0x09, 0xcf, 0x5c, 0x5b, 0xbb, 0xb6, 0x6a, 0xe4, 0x03, 0x4c, 0x36, 0x4c, 0xaa, 0xd9, 0x42, 0xf6,
	0xbf, 0x60, 0x42, 0xe2, 0x73, 0xb0, 0x25, 0xff, 0xc7, 0xb2, 0x6a, 0xba, 0xf2, 0x42, 0xbe, 0xc1,
	0xb4, 0xe6, 0x44, 0xce, 0x33, 0xc1, 0xf0, 0x3d, 0xd8, 0xea, 0xb1, 0xc2, 0x35, 0xe6, 0xa6, 0x3f,
	0x5a, 0x4d, 0x96, 0xf7, 0xcf, 0x5d, 0x6a, 0xac, 0x14, 0xc9, 0x47, 0x98, 0x06, 0x5c, 0x5c, 0xd1,
	0xe1, 0x13, 0x3c, 0x69, 0xc0, 0xaa, 0xc5, 0x0b, 0x18, 0x08, 0x49, 0x65, 0x21, 0x2a, 0xb4, 0xba,
	0xa9, 0xa9, 0x83, 0xe2, 0x0a, 0xcf, 0x05, 0x4c, 0x6b, 0xae, 0xc3, 0x72, 0x01, 0x4f, 0x7f, 0xb0,
	0x94, 0x49, 0xd6, 0xed, 0xfa, 0x19, 0xf0, 0x14, 0xed, 0x30, 0x7e, 0x0b, 0x8e, 0xe2, 0xb6, 0x2a,
	0x64, 0x15, 0x70, 0x44, 0x25, 0xd5, 0xc8, 0x38, 0xd4, 0x67, 0xf2, 0x05, 0x5e, 0xfe, 0xce, 0x53,
	0x4e, 0xa3, 0x1a, 0xeb, 0xf2, 0x5c, 0xdd, 0xf6, 0xc1, 0x56, 0xb4, 0xc0, 0x35, 0x98, 0x1b, 0x26,
	0xd1, 0x6d, 0x96, 0xdf, 0x8e, 0xd3, 0x7b, 0x75, 0x41, 0x29, 0xdd, 0x49, 0x0f, 0xbf, 0x83, 0xa5,
	0x76, 0x8e, 0x27, 0xd0, 0x59, 0x58, 0x9e, 0x77, 0x49, 0xaa, 0x0d, 0xd6, 0x60, 0x06, 0x45, 0xab,
	0x7d, 0x3b, 0x97, 0xd3, 0xf6, 0x67, 0x49, 0x90, 0x1e, 0xfe, 0x84, 0x41, 0xb9, 0x48, 0x7c, 0xdd,
	0x60, 0x0f, 0x52, 0xf0, 0x66, 0x97, 0xc5, 0xda, 0x66, 0x0b, 0xa3, 0x72, 0x81, 0xe5, 0x8e, 0x9f,
	0xb5, 0x7f, 0x44, 0x5d, 0xf4, 0xde, 0x35, 0xc5, 0x47, 0x96, 0x4d, 0x7a, 0xbe, 0xf1, 0x77, 0xa0,
	0xa9, 0xaf, 0x77, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x9d, 0xef, 0xf0, 0xc7, 0x03, 0x00, 0x00,
}
