// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UsersEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersEmpty) Reset()         { *m = UsersEmpty{} }
func (m *UsersEmpty) String() string { return proto.CompactTextString(m) }
func (*UsersEmpty) ProtoMessage()    {}
func (*UsersEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UsersEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersEmpty.Unmarshal(m, b)
}
func (m *UsersEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersEmpty.Marshal(b, m, deterministic)
}
func (m *UsersEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersEmpty.Merge(m, src)
}
func (m *UsersEmpty) XXX_Size() int {
	return xxx_messageInfo_UsersEmpty.Size(m)
}
func (m *UsersEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_UsersEmpty proto.InternalMessageInfo

type RequestUser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Birthday             string   `protobuf:"bytes,3,opt,name=birthday,proto3" json:"birthday,omitempty"`
	IsSaler              bool     `protobuf:"varint,4,opt,name=is_saler,json=isSaler,proto3" json:"is_saler,omitempty"`
	IsBuyer              bool     `protobuf:"varint,5,opt,name=is_buyer,json=isBuyer,proto3" json:"is_buyer,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestUser) Reset()         { *m = RequestUser{} }
func (m *RequestUser) String() string { return proto.CompactTextString(m) }
func (*RequestUser) ProtoMessage()    {}
func (*RequestUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *RequestUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUser.Unmarshal(m, b)
}
func (m *RequestUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUser.Marshal(b, m, deterministic)
}
func (m *RequestUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUser.Merge(m, src)
}
func (m *RequestUser) XXX_Size() int {
	return xxx_messageInfo_RequestUser.Size(m)
}
func (m *RequestUser) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUser.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUser proto.InternalMessageInfo

func (m *RequestUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RequestUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RequestUser) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *RequestUser) GetIsSaler() bool {
	if m != nil {
		return m.IsSaler
	}
	return false
}

func (m *RequestUser) GetIsBuyer() bool {
	if m != nil {
		return m.IsBuyer
	}
	return false
}

func (m *RequestUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResponseUser struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Birthday             string   `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	IsSaler              bool     `protobuf:"varint,5,opt,name=is_saler,json=isSaler,proto3" json:"is_saler,omitempty"`
	IsBuyer              bool     `protobuf:"varint,6,opt,name=is_buyer,json=isBuyer,proto3" json:"is_buyer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseUser) Reset()         { *m = ResponseUser{} }
func (m *ResponseUser) String() string { return proto.CompactTextString(m) }
func (*ResponseUser) ProtoMessage()    {}
func (*ResponseUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *ResponseUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseUser.Unmarshal(m, b)
}
func (m *ResponseUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseUser.Marshal(b, m, deterministic)
}
func (m *ResponseUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseUser.Merge(m, src)
}
func (m *ResponseUser) XXX_Size() int {
	return xxx_messageInfo_ResponseUser.Size(m)
}
func (m *ResponseUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseUser.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseUser proto.InternalMessageInfo

func (m *ResponseUser) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResponseUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResponseUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ResponseUser) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *ResponseUser) GetIsSaler() bool {
	if m != nil {
		return m.IsSaler
	}
	return false
}

func (m *ResponseUser) GetIsBuyer() bool {
	if m != nil {
		return m.IsBuyer
	}
	return false
}

// Read
type GetMeRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMeRequest) Reset()         { *m = GetMeRequest{} }
func (m *GetMeRequest) String() string { return proto.CompactTextString(m) }
func (*GetMeRequest) ProtoMessage()    {}
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *GetMeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMeRequest.Unmarshal(m, b)
}
func (m *GetMeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMeRequest.Marshal(b, m, deterministic)
}
func (m *GetMeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMeRequest.Merge(m, src)
}
func (m *GetMeRequest) XXX_Size() int {
	return xxx_messageInfo_GetMeRequest.Size(m)
}
func (m *GetMeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMeRequest proto.InternalMessageInfo

func (m *GetMeRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetMeResponse struct {
	User                 *ResponseUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetMeResponse) Reset()         { *m = GetMeResponse{} }
func (m *GetMeResponse) String() string { return proto.CompactTextString(m) }
func (*GetMeResponse) ProtoMessage()    {}
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *GetMeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMeResponse.Unmarshal(m, b)
}
func (m *GetMeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMeResponse.Marshal(b, m, deterministic)
}
func (m *GetMeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMeResponse.Merge(m, src)
}
func (m *GetMeResponse) XXX_Size() int {
	return xxx_messageInfo_GetMeResponse.Size(m)
}
func (m *GetMeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMeResponse proto.InternalMessageInfo

func (m *GetMeResponse) GetUser() *ResponseUser {
	if m != nil {
		return m.User
	}
	return nil
}

type GetSingleUserRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSingleUserRequest) Reset()         { *m = GetSingleUserRequest{} }
func (m *GetSingleUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetSingleUserRequest) ProtoMessage()    {}
func (*GetSingleUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *GetSingleUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSingleUserRequest.Unmarshal(m, b)
}
func (m *GetSingleUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSingleUserRequest.Marshal(b, m, deterministic)
}
func (m *GetSingleUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSingleUserRequest.Merge(m, src)
}
func (m *GetSingleUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetSingleUserRequest.Size(m)
}
func (m *GetSingleUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSingleUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSingleUserRequest proto.InternalMessageInfo

func (m *GetSingleUserRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetSingleUserResponse struct {
	User                 *ResponseUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetSingleUserResponse) Reset()         { *m = GetSingleUserResponse{} }
func (m *GetSingleUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetSingleUserResponse) ProtoMessage()    {}
func (*GetSingleUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *GetSingleUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSingleUserResponse.Unmarshal(m, b)
}
func (m *GetSingleUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSingleUserResponse.Marshal(b, m, deterministic)
}
func (m *GetSingleUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSingleUserResponse.Merge(m, src)
}
func (m *GetSingleUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetSingleUserResponse.Size(m)
}
func (m *GetSingleUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSingleUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSingleUserResponse proto.InternalMessageInfo

func (m *GetSingleUserResponse) GetUser() *ResponseUser {
	if m != nil {
		return m.User
	}
	return nil
}

type GetAllUsersResponse struct {
	User                 []*ResponseUser `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetAllUsersResponse) Reset()         { *m = GetAllUsersResponse{} }
func (m *GetAllUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllUsersResponse) ProtoMessage()    {}
func (*GetAllUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *GetAllUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUsersResponse.Unmarshal(m, b)
}
func (m *GetAllUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUsersResponse.Marshal(b, m, deterministic)
}
func (m *GetAllUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUsersResponse.Merge(m, src)
}
func (m *GetAllUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllUsersResponse.Size(m)
}
func (m *GetAllUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUsersResponse proto.InternalMessageInfo

func (m *GetAllUsersResponse) GetUser() []*ResponseUser {
	if m != nil {
		return m.User
	}
	return nil
}

// Create
type UserImage struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserImage) Reset()         { *m = UserImage{} }
func (m *UserImage) String() string { return proto.CompactTextString(m) }
func (*UserImage) ProtoMessage()    {}
func (*UserImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *UserImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserImage.Unmarshal(m, b)
}
func (m *UserImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserImage.Marshal(b, m, deterministic)
}
func (m *UserImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserImage.Merge(m, src)
}
func (m *UserImage) XXX_Size() int {
	return xxx_messageInfo_UserImage.Size(m)
}
func (m *UserImage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserImage.DiscardUnknown(m)
}

var xxx_messageInfo_UserImage proto.InternalMessageInfo

func (m *UserImage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PostMeRequest struct {
	User                 *RequestUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Image                *UserImage   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PostMeRequest) Reset()         { *m = PostMeRequest{} }
func (m *PostMeRequest) String() string { return proto.CompactTextString(m) }
func (*PostMeRequest) ProtoMessage()    {}
func (*PostMeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *PostMeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMeRequest.Unmarshal(m, b)
}
func (m *PostMeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMeRequest.Marshal(b, m, deterministic)
}
func (m *PostMeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMeRequest.Merge(m, src)
}
func (m *PostMeRequest) XXX_Size() int {
	return xxx_messageInfo_PostMeRequest.Size(m)
}
func (m *PostMeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostMeRequest proto.InternalMessageInfo

func (m *PostMeRequest) GetUser() *RequestUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PostMeRequest) GetImage() *UserImage {
	if m != nil {
		return m.Image
	}
	return nil
}

type PostMeResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostMeResponse) Reset()         { *m = PostMeResponse{} }
func (m *PostMeResponse) String() string { return proto.CompactTextString(m) }
func (*PostMeResponse) ProtoMessage()    {}
func (*PostMeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *PostMeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMeResponse.Unmarshal(m, b)
}
func (m *PostMeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMeResponse.Marshal(b, m, deterministic)
}
func (m *PostMeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMeResponse.Merge(m, src)
}
func (m *PostMeResponse) XXX_Size() int {
	return xxx_messageInfo_PostMeResponse.Size(m)
}
func (m *PostMeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostMeResponse proto.InternalMessageInfo

func (m *PostMeResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// Update
type PutMeRequest struct {
	Token                string       `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User                 *RequestUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PutMeRequest) Reset()         { *m = PutMeRequest{} }
func (m *PutMeRequest) String() string { return proto.CompactTextString(m) }
func (*PutMeRequest) ProtoMessage()    {}
func (*PutMeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *PutMeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMeRequest.Unmarshal(m, b)
}
func (m *PutMeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMeRequest.Marshal(b, m, deterministic)
}
func (m *PutMeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMeRequest.Merge(m, src)
}
func (m *PutMeRequest) XXX_Size() int {
	return xxx_messageInfo_PutMeRequest.Size(m)
}
func (m *PutMeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutMeRequest proto.InternalMessageInfo

func (m *PutMeRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PutMeRequest) GetUser() *RequestUser {
	if m != nil {
		return m.User
	}
	return nil
}

type PutMeResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutMeResponse) Reset()         { *m = PutMeResponse{} }
func (m *PutMeResponse) String() string { return proto.CompactTextString(m) }
func (*PutMeResponse) ProtoMessage()    {}
func (*PutMeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *PutMeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMeResponse.Unmarshal(m, b)
}
func (m *PutMeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMeResponse.Marshal(b, m, deterministic)
}
func (m *PutMeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMeResponse.Merge(m, src)
}
func (m *PutMeResponse) XXX_Size() int {
	return xxx_messageInfo_PutMeResponse.Size(m)
}
func (m *PutMeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutMeResponse proto.InternalMessageInfo

func (m *PutMeResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// Delete
type DeleteMeRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMeRequest) Reset()         { *m = DeleteMeRequest{} }
func (m *DeleteMeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMeRequest) ProtoMessage()    {}
func (*DeleteMeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{13}
}

func (m *DeleteMeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMeRequest.Unmarshal(m, b)
}
func (m *DeleteMeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMeRequest.Merge(m, src)
}
func (m *DeleteMeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMeRequest.Size(m)
}
func (m *DeleteMeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMeRequest proto.InternalMessageInfo

func (m *DeleteMeRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DeleteMeResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMeResponse) Reset()         { *m = DeleteMeResponse{} }
func (m *DeleteMeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMeResponse) ProtoMessage()    {}
func (*DeleteMeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{14}
}

func (m *DeleteMeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMeResponse.Unmarshal(m, b)
}
func (m *DeleteMeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMeResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMeResponse.Merge(m, src)
}
func (m *DeleteMeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMeResponse.Size(m)
}
func (m *DeleteMeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMeResponse proto.InternalMessageInfo

func (m *DeleteMeResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*UsersEmpty)(nil), "protocol.UsersEmpty")
	proto.RegisterType((*RequestUser)(nil), "protocol.RequestUser")
	proto.RegisterType((*ResponseUser)(nil), "protocol.ResponseUser")
	proto.RegisterType((*GetMeRequest)(nil), "protocol.GetMeRequest")
	proto.RegisterType((*GetMeResponse)(nil), "protocol.GetMeResponse")
	proto.RegisterType((*GetSingleUserRequest)(nil), "protocol.GetSingleUserRequest")
	proto.RegisterType((*GetSingleUserResponse)(nil), "protocol.GetSingleUserResponse")
	proto.RegisterType((*GetAllUsersResponse)(nil), "protocol.GetAllUsersResponse")
	proto.RegisterType((*UserImage)(nil), "protocol.UserImage")
	proto.RegisterType((*PostMeRequest)(nil), "protocol.PostMeRequest")
	proto.RegisterType((*PostMeResponse)(nil), "protocol.PostMeResponse")
	proto.RegisterType((*PutMeRequest)(nil), "protocol.PutMeRequest")
	proto.RegisterType((*PutMeResponse)(nil), "protocol.PutMeResponse")
	proto.RegisterType((*DeleteMeRequest)(nil), "protocol.DeleteMeRequest")
	proto.RegisterType((*DeleteMeResponse)(nil), "protocol.DeleteMeResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4b, 0x6b, 0xdb, 0x4c,
	0x14, 0xb5, 0x25, 0x4b, 0x51, 0xae, 0xe5, 0x7c, 0x1f, 0x13, 0x27, 0x51, 0x04, 0x6d, 0xc2, 0x50,
	0x9a, 0xc7, 0xc2, 0x05, 0x77, 0x97, 0xd2, 0x45, 0x9a, 0x14, 0x93, 0x45, 0x69, 0x50, 0xe8, 0x3a,
	0xc8, 0xd5, 0x25, 0x15, 0x95, 0x2d, 0x57, 0x33, 0xa2, 0xf8, 0xaf, 0x14, 0xba, 0xec, 0xff, 0x2c,
	0xf3, 0x90, 0x3c, 0xf2, 0x23, 0x86, 0xae, 0xac, 0x33, 0xf7, 0xce, 0xb9, 0x67, 0xee, 0x39, 0x18,
	0xa0, 0x64, 0x58, 0x0c, 0x66, 0x45, 0xce, 0x73, 0xe2, 0xc9, 0x9f, 0xaf, 0x79, 0x46, 0x7d, 0x80,
	0x2f, 0x0c, 0x0b, 0xf6, 0x71, 0x32, 0xe3, 0x73, 0xfa, 0xa7, 0x0d, 0xdd, 0x08, 0x7f, 0x94, 0xc8,
	0xb8, 0x38, 0x25, 0x04, 0x3a, 0xd3, 0x78, 0x82, 0x41, 0xfb, 0xb4, 0x7d, 0xbe, 0x1b, 0xc9, 0x6f,
	0xd2, 0x07, 0x07, 0x27, 0x71, 0x9a, 0x05, 0x96, 0x3c, 0x54, 0x80, 0x84, 0xe0, 0x8d, 0xd3, 0x82,
	0x7f, 0x4b, 0xe2, 0x79, 0x60, 0xcb, 0x42, 0x8d, 0xc9, 0x31, 0x78, 0x29, 0x7b, 0x64, 0x71, 0x86,
	0x45, 0xd0, 0x39, 0x6d, 0x9f, 0x7b, 0xd1, 0x4e, 0xca, 0x1e, 0x04, 0xd4, 0xa5, 0x71, 0x39, 0xc7,
	0x22, 0x70, 0xaa, 0xd2, 0x07, 0x01, 0x05, 0xe3, 0x2c, 0x66, 0xec, 0x67, 0x5e, 0x24, 0x81, 0xab,
	0x18, 0x2b, 0x4c, 0x7f, 0xb5, 0xc1, 0x8f, 0x90, 0xcd, 0xf2, 0x29, 0x43, 0x29, 0x74, 0x0f, 0xac,
	0x34, 0x91, 0x32, 0xed, 0xc8, 0x4a, 0x93, 0x5a, 0xb8, 0xb5, 0x4e, 0xb8, 0xbd, 0x49, 0x78, 0xe7,
	0x19, 0xe1, 0xce, 0x66, 0xe1, 0x6e, 0x43, 0x38, 0x7d, 0x05, 0xfe, 0x08, 0xf9, 0x27, 0xd4, 0x8b,
	0x14, 0x73, 0x79, 0xfe, 0x1d, 0xa7, 0x7a, 0x8b, 0x0a, 0xd0, 0x77, 0xd0, 0xd3, 0x5d, 0xea, 0x19,
	0xe4, 0x12, 0x3a, 0xc2, 0x21, 0xd9, 0xd5, 0x1d, 0x1e, 0x0e, 0x2a, 0x8b, 0x06, 0xe6, 0x43, 0x23,
	0xd9, 0x43, 0xdf, 0x40, 0x7f, 0x84, 0xfc, 0x21, 0x9d, 0x3e, 0x65, 0xea, 0x58, 0x8f, 0x3a, 0x82,
	0x1d, 0x51, 0x7f, 0xac, 0x77, 0xe1, 0x0a, 0x78, 0x97, 0xd0, 0x1b, 0x38, 0x58, 0xba, 0xf0, 0x0f,
	0x53, 0xaf, 0x61, 0x7f, 0x84, 0xfc, 0x3a, 0xcb, 0x64, 0x62, 0xd6, 0x50, 0xd8, 0x5b, 0x29, 0x4e,
	0x60, 0x57, 0xa0, 0xbb, 0x49, 0xfc, 0x84, 0xc2, 0xa4, 0x24, 0xe6, 0xb1, 0x9c, 0xed, 0x47, 0xf2,
	0x9b, 0x22, 0xf4, 0xee, 0x73, 0x66, 0x6c, 0xef, 0xa2, 0x21, 0xf0, 0xc0, 0x64, 0xaf, 0x73, 0xaa,
	0xc8, 0xc9, 0x05, 0x38, 0xa9, 0x20, 0x96, 0xae, 0x77, 0x87, 0xfb, 0x8b, 0xde, 0x7a, 0x66, 0xa4,
	0x3a, 0xe8, 0x6b, 0xd8, 0xab, 0xc6, 0xe8, 0x57, 0xac, 0x77, 0xe9, 0x33, 0xf8, 0xf7, 0xe5, 0x36,
	0x2f, 0x6b, 0x8d, 0xd6, 0x56, 0x8d, 0xf4, 0x0c, 0x7a, 0x9a, 0x50, 0xcf, 0x3d, 0x04, 0x97, 0xf1,
	0x98, 0x97, 0x4c, 0x53, 0x6a, 0x44, 0xcf, 0xe0, 0xbf, 0x5b, 0xcc, 0x90, 0xe3, 0xb6, 0x20, 0x5d,
	0xc2, 0xff, 0x8b, 0xc6, 0xe7, 0x49, 0x87, 0xbf, 0x6d, 0x70, 0xa4, 0x79, 0xe4, 0x0a, 0x1c, 0x19,
	0x3f, 0x62, 0xf8, 0x65, 0xa6, 0x36, 0x3c, 0x5a, 0x39, 0x57, 0xdc, 0xb4, 0x45, 0x22, 0x19, 0xdd,
	0x45, 0x98, 0xc8, 0xcb, 0x46, 0xef, 0x4a, 0x2c, 0xc3, 0x93, 0x8d, 0xf5, 0x9a, 0xf3, 0x16, 0xba,
	0x46, 0xb6, 0x48, 0xbf, 0xe9, 0x9d, 0xfa, 0x7b, 0x0a, 0x5f, 0x34, 0x78, 0x96, 0x83, 0x48, 0x5b,
	0xe4, 0x3d, 0xb8, 0xca, 0x56, 0x62, 0xc8, 0x6f, 0xe4, 0x29, 0x0c, 0x56, 0x0b, 0xf5, 0xf5, 0x2b,
	0x70, 0xa4, 0x39, 0xe6, 0x52, 0x4c, 0xfb, 0xcd, 0xa5, 0x34, 0x5c, 0xa4, 0x2d, 0x72, 0x03, 0x5e,
	0x65, 0x03, 0x39, 0x5e, 0xb4, 0x2d, 0x79, 0x18, 0x86, 0xeb, 0x4a, 0x15, 0xc9, 0xd8, 0x95, 0xc5,
	0xb7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x4b, 0x7d, 0x7e, 0xac, 0x05, 0x00, 0x00,
}
