// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestUser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Birthday             string   `protobuf:"bytes,3,opt,name=birthday,proto3" json:"birthday,omitempty"`
	IsSaler              bool     `protobuf:"varint,4,opt,name=is_saler,json=isSaler,proto3" json:"is_saler,omitempty"`
	IsBuyer              bool     `protobuf:"varint,5,opt,name=is_buyer,json=isBuyer,proto3" json:"is_buyer,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestUser) Reset()         { *m = RequestUser{} }
func (m *RequestUser) String() string { return proto.CompactTextString(m) }
func (*RequestUser) ProtoMessage()    {}
func (*RequestUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *RequestUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUser.Unmarshal(m, b)
}
func (m *RequestUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUser.Marshal(b, m, deterministic)
}
func (m *RequestUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUser.Merge(m, src)
}
func (m *RequestUser) XXX_Size() int {
	return xxx_messageInfo_RequestUser.Size(m)
}
func (m *RequestUser) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUser.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUser proto.InternalMessageInfo

func (m *RequestUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RequestUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RequestUser) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *RequestUser) GetIsSaler() bool {
	if m != nil {
		return m.IsSaler
	}
	return false
}

func (m *RequestUser) GetIsBuyer() bool {
	if m != nil {
		return m.IsBuyer
	}
	return false
}

func (m *RequestUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResponseUser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Birthday             string   `protobuf:"bytes,3,opt,name=birthday,proto3" json:"birthday,omitempty"`
	IsSaler              bool     `protobuf:"varint,4,opt,name=is_saler,json=isSaler,proto3" json:"is_saler,omitempty"`
	IsBuyer              bool     `protobuf:"varint,5,opt,name=is_buyer,json=isBuyer,proto3" json:"is_buyer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseUser) Reset()         { *m = ResponseUser{} }
func (m *ResponseUser) String() string { return proto.CompactTextString(m) }
func (*ResponseUser) ProtoMessage()    {}
func (*ResponseUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *ResponseUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseUser.Unmarshal(m, b)
}
func (m *ResponseUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseUser.Marshal(b, m, deterministic)
}
func (m *ResponseUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseUser.Merge(m, src)
}
func (m *ResponseUser) XXX_Size() int {
	return xxx_messageInfo_ResponseUser.Size(m)
}
func (m *ResponseUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseUser.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseUser proto.InternalMessageInfo

func (m *ResponseUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResponseUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ResponseUser) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *ResponseUser) GetIsSaler() bool {
	if m != nil {
		return m.IsSaler
	}
	return false
}

func (m *ResponseUser) GetIsBuyer() bool {
	if m != nil {
		return m.IsBuyer
	}
	return false
}

type GetUserRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetUserResponse struct {
	User                 *ResponseUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *ResponseUser {
	if m != nil {
		return m.User
	}
	return nil
}

type PostUserRequest struct {
	User                 *RequestUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PostUserRequest) Reset()         { *m = PostUserRequest{} }
func (m *PostUserRequest) String() string { return proto.CompactTextString(m) }
func (*PostUserRequest) ProtoMessage()    {}
func (*PostUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *PostUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostUserRequest.Unmarshal(m, b)
}
func (m *PostUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostUserRequest.Marshal(b, m, deterministic)
}
func (m *PostUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostUserRequest.Merge(m, src)
}
func (m *PostUserRequest) XXX_Size() int {
	return xxx_messageInfo_PostUserRequest.Size(m)
}
func (m *PostUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostUserRequest proto.InternalMessageInfo

func (m *PostUserRequest) GetUser() *RequestUser {
	if m != nil {
		return m.User
	}
	return nil
}

type PostUserResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostUserResponse) Reset()         { *m = PostUserResponse{} }
func (m *PostUserResponse) String() string { return proto.CompactTextString(m) }
func (*PostUserResponse) ProtoMessage()    {}
func (*PostUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *PostUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostUserResponse.Unmarshal(m, b)
}
func (m *PostUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostUserResponse.Marshal(b, m, deterministic)
}
func (m *PostUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostUserResponse.Merge(m, src)
}
func (m *PostUserResponse) XXX_Size() int {
	return xxx_messageInfo_PostUserResponse.Size(m)
}
func (m *PostUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostUserResponse proto.InternalMessageInfo

func (m *PostUserResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type PutUserRequest struct {
	Token                string       `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User                 *RequestUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PutUserRequest) Reset()         { *m = PutUserRequest{} }
func (m *PutUserRequest) String() string { return proto.CompactTextString(m) }
func (*PutUserRequest) ProtoMessage()    {}
func (*PutUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *PutUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutUserRequest.Unmarshal(m, b)
}
func (m *PutUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutUserRequest.Marshal(b, m, deterministic)
}
func (m *PutUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutUserRequest.Merge(m, src)
}
func (m *PutUserRequest) XXX_Size() int {
	return xxx_messageInfo_PutUserRequest.Size(m)
}
func (m *PutUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutUserRequest proto.InternalMessageInfo

func (m *PutUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PutUserRequest) GetUser() *RequestUser {
	if m != nil {
		return m.User
	}
	return nil
}

type PutUserResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutUserResponse) Reset()         { *m = PutUserResponse{} }
func (m *PutUserResponse) String() string { return proto.CompactTextString(m) }
func (*PutUserResponse) ProtoMessage()    {}
func (*PutUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *PutUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutUserResponse.Unmarshal(m, b)
}
func (m *PutUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutUserResponse.Marshal(b, m, deterministic)
}
func (m *PutUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutUserResponse.Merge(m, src)
}
func (m *PutUserResponse) XXX_Size() int {
	return xxx_messageInfo_PutUserResponse.Size(m)
}
func (m *PutUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutUserResponse proto.InternalMessageInfo

func (m *PutUserResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type DeleteUserRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DeleteUserResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UserImage struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserImage) Reset()         { *m = UserImage{} }
func (m *UserImage) String() string { return proto.CompactTextString(m) }
func (*UserImage) ProtoMessage()    {}
func (*UserImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *UserImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserImage.Unmarshal(m, b)
}
func (m *UserImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserImage.Marshal(b, m, deterministic)
}
func (m *UserImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserImage.Merge(m, src)
}
func (m *UserImage) XXX_Size() int {
	return xxx_messageInfo_UserImage.Size(m)
}
func (m *UserImage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserImage.DiscardUnknown(m)
}

var xxx_messageInfo_UserImage proto.InternalMessageInfo

func (m *UserImage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadUserImageResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadUserImageResponse) Reset()         { *m = UploadUserImageResponse{} }
func (m *UploadUserImageResponse) String() string { return proto.CompactTextString(m) }
func (*UploadUserImageResponse) ProtoMessage()    {}
func (*UploadUserImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *UploadUserImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadUserImageResponse.Unmarshal(m, b)
}
func (m *UploadUserImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadUserImageResponse.Marshal(b, m, deterministic)
}
func (m *UploadUserImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadUserImageResponse.Merge(m, src)
}
func (m *UploadUserImageResponse) XXX_Size() int {
	return xxx_messageInfo_UploadUserImageResponse.Size(m)
}
func (m *UploadUserImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadUserImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadUserImageResponse proto.InternalMessageInfo

func (m *UploadUserImageResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestUser)(nil), "protocol.RequestUser")
	proto.RegisterType((*ResponseUser)(nil), "protocol.ResponseUser")
	proto.RegisterType((*GetUserRequest)(nil), "protocol.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "protocol.GetUserResponse")
	proto.RegisterType((*PostUserRequest)(nil), "protocol.PostUserRequest")
	proto.RegisterType((*PostUserResponse)(nil), "protocol.PostUserResponse")
	proto.RegisterType((*PutUserRequest)(nil), "protocol.PutUserRequest")
	proto.RegisterType((*PutUserResponse)(nil), "protocol.PutUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "protocol.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "protocol.DeleteUserResponse")
	proto.RegisterType((*UserImage)(nil), "protocol.UserImage")
	proto.RegisterType((*UploadUserImageResponse)(nil), "protocol.UploadUserImageResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x52, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x6d, 0xda, 0x34, 0x66, 0x6f, 0x97, 0xad, 0x8e, 0xba, 0x66, 0xa3, 0xe0, 0x3a, 0x0f, 0x92,
	0x8a, 0x14, 0x5c, 0x5f, 0x2b, 0x82, 0x28, 0xcb, 0xbe, 0xd5, 0xc8, 0x3e, 0xcb, 0xd4, 0x5c, 0x34,
	0x98, 0x76, 0x62, 0x66, 0x82, 0xf4, 0x2f, 0xf8, 0x3f, 0xfc, 0x4b, 0xfe, 0x1e, 0x99, 0x8f, 0x4e,
	0x92, 0x1a, 0xc8, 0xa3, 0x4f, 0xc9, 0x9d, 0x7b, 0xee, 0x39, 0x77, 0xce, 0x19, 0x80, 0x5a, 0x60,
	0xb5, 0x2c, 0x2b, 0x2e, 0x39, 0x09, 0xf5, 0xe7, 0x0b, 0x2f, 0xe8, 0x6f, 0x0f, 0x66, 0x29, 0xfe,
	0xa8, 0x51, 0xc8, 0x5b, 0x81, 0x15, 0x21, 0xe0, 0xef, 0xd8, 0x16, 0x23, 0xef, 0xd2, 0x4b, 0x4e,
	0x52, 0xfd, 0x4f, 0x1e, 0xc0, 0x14, 0xb7, 0x2c, 0x2f, 0xa2, 0xb1, 0x3e, 0x34, 0x05, 0x89, 0x21,
	0xdc, 0xe4, 0x95, 0xfc, 0x96, 0xb1, 0x7d, 0x34, 0xd1, 0x0d, 0x57, 0x93, 0x0b, 0x08, 0x73, 0xf1,
	0x59, 0xb0, 0x02, 0xab, 0xc8, 0xbf, 0xf4, 0x92, 0x30, 0xbd, 0x93, 0x8b, 0x4f, 0xaa, 0xb4, 0xad,
	0x4d, 0xbd, 0xc7, 0x2a, 0x9a, 0x1e, 0x5a, 0xef, 0x54, 0xa9, 0x18, 0x4b, 0x26, 0xc4, 0x4f, 0x5e,
	0x65, 0x51, 0x60, 0x18, 0x0f, 0x35, 0xfd, 0xe5, 0xc1, 0x69, 0x8a, 0xa2, 0xe4, 0x3b, 0x81, 0xff,
	0x7b, 0x51, 0xfa, 0x1c, 0xce, 0xae, 0x51, 0xfb, 0x65, 0xad, 0x53, 0xca, 0x92, 0x7f, 0xc7, 0x9d,
	0x5d, 0xc7, 0x14, 0xf4, 0x0d, 0xcc, 0x1d, 0xce, 0xac, 0x4e, 0x5e, 0x80, 0xaf, 0x72, 0xd0, 0xb8,
	0xd9, 0xd5, 0xf9, 0xf2, 0x10, 0xc4, 0xb2, 0x7d, 0xb9, 0x54, 0x63, 0xe8, 0x0a, 0xe6, 0x6b, 0x2e,
	0x3a, 0x3a, 0x8b, 0xce, 0xf8, 0xc3, 0xf6, 0xb8, 0xcb, 0xd0, 0x4e, 0x27, 0x70, 0xb7, 0x99, 0xb6,
	0xea, 0xfd, 0x6b, 0x7e, 0x84, 0xb3, 0x75, 0x3d, 0x7c, 0x1d, 0x27, 0x3e, 0x1e, 0x16, 0x5f, 0xc0,
	0xdc, 0x51, 0x5a, 0xed, 0x73, 0x08, 0x84, 0x64, 0xb2, 0x16, 0x96, 0xd4, 0x56, 0x74, 0x01, 0xf7,
	0xde, 0x63, 0x81, 0x12, 0x87, 0xfd, 0x7c, 0x09, 0xa4, 0x0d, 0x1d, 0x20, 0x7e, 0x0a, 0x27, 0x0a,
	0x77, 0xb3, 0x65, 0x5f, 0x51, 0x3d, 0x97, 0x8c, 0x49, 0xa6, 0x21, 0xa7, 0xa9, 0xfe, 0xa7, 0xaf,
	0xe0, 0xd1, 0x6d, 0x59, 0x70, 0x96, 0x39, 0xd8, 0x10, 0xe7, 0xd5, 0x9f, 0x31, 0x4c, 0x15, 0x5a,
	0x90, 0x15, 0x4c, 0xae, 0x51, 0x92, 0xa8, 0x71, 0xa1, 0xfb, 0x24, 0xe2, 0x8b, 0x9e, 0x8e, 0x61,
	0xa7, 0x23, 0xf2, 0x16, 0x7c, 0x15, 0x0e, 0x69, 0x81, 0x8e, 0xa2, 0x8e, 0xe3, 0xbe, 0x96, 0x23,
	0x58, 0xc1, 0x64, 0x5d, 0x77, 0xe4, 0xbb, 0x11, 0xb6, 0xe5, 0x8f, 0x92, 0xa0, 0x23, 0xf2, 0x01,
	0x02, 0x63, 0x24, 0x79, 0xdc, 0xc0, 0xfe, 0x49, 0x21, 0x7e, 0xd2, 0xdf, 0x74, 0x34, 0x37, 0x30,
	0x33, 0x06, 0x1a, 0x8f, 0xef, 0x37, 0x70, 0xe7, 0x68, 0xfc, 0xac, 0x75, 0xd8, 0x6f, 0x36, 0x1d,
	0x25, 0xde, 0x26, 0xd0, 0xa8, 0xd7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x91, 0x34, 0x5f, 0x11,
	0xa6, 0x04, 0x00, 0x00,
}
