// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vegetable.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vegetable struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fee                  string   `protobuf:"bytes,2,opt,name=fee,proto3" json:"fee,omitempty"`
	IsChemical           bool     `protobuf:"varint,3,opt,name=is_chemical,json=isChemical,proto3" json:"is_chemical,omitempty"`
	ImagePath            string   `protobuf:"bytes,4,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	ProductionDate       string   `protobuf:"bytes,5,opt,name=production_date,json=productionDate,proto3" json:"production_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vegetable) Reset()         { *m = Vegetable{} }
func (m *Vegetable) String() string { return proto.CompactTextString(m) }
func (*Vegetable) ProtoMessage()    {}
func (*Vegetable) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{0}
}

func (m *Vegetable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vegetable.Unmarshal(m, b)
}
func (m *Vegetable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vegetable.Marshal(b, m, deterministic)
}
func (m *Vegetable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vegetable.Merge(m, src)
}
func (m *Vegetable) XXX_Size() int {
	return xxx_messageInfo_Vegetable.Size(m)
}
func (m *Vegetable) XXX_DiscardUnknown() {
	xxx_messageInfo_Vegetable.DiscardUnknown(m)
}

var xxx_messageInfo_Vegetable proto.InternalMessageInfo

func (m *Vegetable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vegetable) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *Vegetable) GetIsChemical() bool {
	if m != nil {
		return m.IsChemical
	}
	return false
}

func (m *Vegetable) GetImagePath() string {
	if m != nil {
		return m.ImagePath
	}
	return ""
}

func (m *Vegetable) GetProductionDate() string {
	if m != nil {
		return m.ProductionDate
	}
	return ""
}

type GetVegetableRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVegetableRequest) Reset()         { *m = GetVegetableRequest{} }
func (m *GetVegetableRequest) String() string { return proto.CompactTextString(m) }
func (*GetVegetableRequest) ProtoMessage()    {}
func (*GetVegetableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{1}
}

func (m *GetVegetableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVegetableRequest.Unmarshal(m, b)
}
func (m *GetVegetableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVegetableRequest.Marshal(b, m, deterministic)
}
func (m *GetVegetableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVegetableRequest.Merge(m, src)
}
func (m *GetVegetableRequest) XXX_Size() int {
	return xxx_messageInfo_GetVegetableRequest.Size(m)
}
func (m *GetVegetableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVegetableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVegetableRequest proto.InternalMessageInfo

func (m *GetVegetableRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetVegetableResponse struct {
	Vegetables           []*Vegetable `protobuf:"bytes,1,rep,name=vegetables,proto3" json:"vegetables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetVegetableResponse) Reset()         { *m = GetVegetableResponse{} }
func (m *GetVegetableResponse) String() string { return proto.CompactTextString(m) }
func (*GetVegetableResponse) ProtoMessage()    {}
func (*GetVegetableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{2}
}

func (m *GetVegetableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVegetableResponse.Unmarshal(m, b)
}
func (m *GetVegetableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVegetableResponse.Marshal(b, m, deterministic)
}
func (m *GetVegetableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVegetableResponse.Merge(m, src)
}
func (m *GetVegetableResponse) XXX_Size() int {
	return xxx_messageInfo_GetVegetableResponse.Size(m)
}
func (m *GetVegetableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVegetableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVegetableResponse proto.InternalMessageInfo

func (m *GetVegetableResponse) GetVegetables() []*Vegetable {
	if m != nil {
		return m.Vegetables
	}
	return nil
}

type PostVegetableRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostVegetableRequest) Reset()         { *m = PostVegetableRequest{} }
func (m *PostVegetableRequest) String() string { return proto.CompactTextString(m) }
func (*PostVegetableRequest) ProtoMessage()    {}
func (*PostVegetableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{3}
}

func (m *PostVegetableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostVegetableRequest.Unmarshal(m, b)
}
func (m *PostVegetableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostVegetableRequest.Marshal(b, m, deterministic)
}
func (m *PostVegetableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostVegetableRequest.Merge(m, src)
}
func (m *PostVegetableRequest) XXX_Size() int {
	return xxx_messageInfo_PostVegetableRequest.Size(m)
}
func (m *PostVegetableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostVegetableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostVegetableRequest proto.InternalMessageInfo

func (m *PostVegetableRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type PostVegetableResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostVegetableResponse) Reset()         { *m = PostVegetableResponse{} }
func (m *PostVegetableResponse) String() string { return proto.CompactTextString(m) }
func (*PostVegetableResponse) ProtoMessage()    {}
func (*PostVegetableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{4}
}

func (m *PostVegetableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostVegetableResponse.Unmarshal(m, b)
}
func (m *PostVegetableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostVegetableResponse.Marshal(b, m, deterministic)
}
func (m *PostVegetableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostVegetableResponse.Merge(m, src)
}
func (m *PostVegetableResponse) XXX_Size() int {
	return xxx_messageInfo_PostVegetableResponse.Size(m)
}
func (m *PostVegetableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostVegetableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostVegetableResponse proto.InternalMessageInfo

func (m *PostVegetableResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type PutVegetableRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutVegetableRequest) Reset()         { *m = PutVegetableRequest{} }
func (m *PutVegetableRequest) String() string { return proto.CompactTextString(m) }
func (*PutVegetableRequest) ProtoMessage()    {}
func (*PutVegetableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{5}
}

func (m *PutVegetableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutVegetableRequest.Unmarshal(m, b)
}
func (m *PutVegetableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutVegetableRequest.Marshal(b, m, deterministic)
}
func (m *PutVegetableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutVegetableRequest.Merge(m, src)
}
func (m *PutVegetableRequest) XXX_Size() int {
	return xxx_messageInfo_PutVegetableRequest.Size(m)
}
func (m *PutVegetableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutVegetableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutVegetableRequest proto.InternalMessageInfo

func (m *PutVegetableRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type PutVegetableResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutVegetableResponse) Reset()         { *m = PutVegetableResponse{} }
func (m *PutVegetableResponse) String() string { return proto.CompactTextString(m) }
func (*PutVegetableResponse) ProtoMessage()    {}
func (*PutVegetableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{6}
}

func (m *PutVegetableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutVegetableResponse.Unmarshal(m, b)
}
func (m *PutVegetableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutVegetableResponse.Marshal(b, m, deterministic)
}
func (m *PutVegetableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutVegetableResponse.Merge(m, src)
}
func (m *PutVegetableResponse) XXX_Size() int {
	return xxx_messageInfo_PutVegetableResponse.Size(m)
}
func (m *PutVegetableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutVegetableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutVegetableResponse proto.InternalMessageInfo

func (m *PutVegetableResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type DeleteVegetableRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVegetableRequest) Reset()         { *m = DeleteVegetableRequest{} }
func (m *DeleteVegetableRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteVegetableRequest) ProtoMessage()    {}
func (*DeleteVegetableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{7}
}

func (m *DeleteVegetableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVegetableRequest.Unmarshal(m, b)
}
func (m *DeleteVegetableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVegetableRequest.Marshal(b, m, deterministic)
}
func (m *DeleteVegetableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVegetableRequest.Merge(m, src)
}
func (m *DeleteVegetableRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteVegetableRequest.Size(m)
}
func (m *DeleteVegetableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVegetableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVegetableRequest proto.InternalMessageInfo

func (m *DeleteVegetableRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DeleteVegetableResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVegetableResponse) Reset()         { *m = DeleteVegetableResponse{} }
func (m *DeleteVegetableResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteVegetableResponse) ProtoMessage()    {}
func (*DeleteVegetableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{8}
}

func (m *DeleteVegetableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVegetableResponse.Unmarshal(m, b)
}
func (m *DeleteVegetableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVegetableResponse.Marshal(b, m, deterministic)
}
func (m *DeleteVegetableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVegetableResponse.Merge(m, src)
}
func (m *DeleteVegetableResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteVegetableResponse.Size(m)
}
func (m *DeleteVegetableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVegetableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVegetableResponse proto.InternalMessageInfo

func (m *DeleteVegetableResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type VegetableImage struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VegetableImage) Reset()         { *m = VegetableImage{} }
func (m *VegetableImage) String() string { return proto.CompactTextString(m) }
func (*VegetableImage) ProtoMessage()    {}
func (*VegetableImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{9}
}

func (m *VegetableImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VegetableImage.Unmarshal(m, b)
}
func (m *VegetableImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VegetableImage.Marshal(b, m, deterministic)
}
func (m *VegetableImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VegetableImage.Merge(m, src)
}
func (m *VegetableImage) XXX_Size() int {
	return xxx_messageInfo_VegetableImage.Size(m)
}
func (m *VegetableImage) XXX_DiscardUnknown() {
	xxx_messageInfo_VegetableImage.DiscardUnknown(m)
}

var xxx_messageInfo_VegetableImage proto.InternalMessageInfo

func (m *VegetableImage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadVegetableImageResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadVegetableImageResponse) Reset()         { *m = UploadVegetableImageResponse{} }
func (m *UploadVegetableImageResponse) String() string { return proto.CompactTextString(m) }
func (*UploadVegetableImageResponse) ProtoMessage()    {}
func (*UploadVegetableImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{10}
}

func (m *UploadVegetableImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadVegetableImageResponse.Unmarshal(m, b)
}
func (m *UploadVegetableImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadVegetableImageResponse.Marshal(b, m, deterministic)
}
func (m *UploadVegetableImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadVegetableImageResponse.Merge(m, src)
}
func (m *UploadVegetableImageResponse) XXX_Size() int {
	return xxx_messageInfo_UploadVegetableImageResponse.Size(m)
}
func (m *UploadVegetableImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadVegetableImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadVegetableImageResponse proto.InternalMessageInfo

func (m *UploadVegetableImageResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Vegetable)(nil), "protocol.Vegetable")
	proto.RegisterType((*GetVegetableRequest)(nil), "protocol.GetVegetableRequest")
	proto.RegisterType((*GetVegetableResponse)(nil), "protocol.GetVegetableResponse")
	proto.RegisterType((*PostVegetableRequest)(nil), "protocol.PostVegetableRequest")
	proto.RegisterType((*PostVegetableResponse)(nil), "protocol.PostVegetableResponse")
	proto.RegisterType((*PutVegetableRequest)(nil), "protocol.PutVegetableRequest")
	proto.RegisterType((*PutVegetableResponse)(nil), "protocol.PutVegetableResponse")
	proto.RegisterType((*DeleteVegetableRequest)(nil), "protocol.DeleteVegetableRequest")
	proto.RegisterType((*DeleteVegetableResponse)(nil), "protocol.DeleteVegetableResponse")
	proto.RegisterType((*VegetableImage)(nil), "protocol.VegetableImage")
	proto.RegisterType((*UploadVegetableImageResponse)(nil), "protocol.UploadVegetableImageResponse")
}

func init() { proto.RegisterFile("vegetable.proto", fileDescriptor_50c7ebee713ee9ad) }

var fileDescriptor_50c7ebee713ee9ad = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x6f, 0x8f, 0x93, 0x40,
	0x10, 0xc6, 0x8b, 0xf4, 0x9a, 0xeb, 0xd4, 0xdc, 0x99, 0x3d, 0x3c, 0x09, 0xb1, 0x16, 0x37, 0x46,
	0x49, 0x34, 0x18, 0xdb, 0xc4, 0x2f, 0x60, 0xd3, 0xa6, 0xf1, 0x85, 0x04, 0xa3, 0x6f, 0x9b, 0x2d,
	0x8c, 0x2d, 0x91, 0xb2, 0xd8, 0x5d, 0xfc, 0x16, 0x7e, 0x01, 0x3f, 0xad, 0x61, 0xa1, 0x50, 0x3c,
	0xfa, 0xe7, 0x15, 0xcb, 0xcc, 0x6f, 0x9f, 0x99, 0x9d, 0x67, 0xe0, 0xf6, 0x37, 0xae, 0x51, 0xb2,
	0x55, 0x8c, 0x6e, 0xba, 0xe3, 0x92, 0x93, 0x6b, 0xf5, 0x09, 0x78, 0x4c, 0xff, 0x6a, 0xd0, 0xff,
	0xbe, 0xcf, 0x12, 0x02, 0xdd, 0x84, 0x6d, 0xd1, 0xd4, 0x6c, 0xcd, 0xe9, 0xfb, 0xea, 0x4c, 0x9e,
	0x80, 0xfe, 0x03, 0xd1, 0x7c, 0xa4, 0x42, 0xf9, 0x91, 0x8c, 0x60, 0x10, 0x89, 0x65, 0xb0, 0xc1,
	0x6d, 0x14, 0xb0, 0xd8, 0xd4, 0x6d, 0xcd, 0xb9, 0xf6, 0x21, 0x12, 0x9f, 0xca, 0x08, 0x19, 0x02,
	0x44, 0x5b, 0xb6, 0xc6, 0x65, 0xca, 0xe4, 0xc6, 0xec, 0xaa, 0x9b, 0x7d, 0x15, 0xf1, 0x98, 0xdc,
	0x90, 0x37, 0x70, 0x9b, 0xee, 0x78, 0x98, 0x05, 0x32, 0xe2, 0xc9, 0x32, 0x64, 0x12, 0xcd, 0x2b,
	0xc5, 0xdc, 0xd4, 0xe1, 0x29, 0x93, 0x48, 0xdf, 0xc2, 0xdd, 0x1c, 0x65, 0xd5, 0x9e, 0x8f, 0xbf,
	0x32, 0x14, 0x92, 0x18, 0x70, 0x25, 0xf9, 0x4f, 0x4c, 0xca, 0x36, 0x8b, 0x1f, 0xfa, 0x19, 0x8c,
	0x26, 0x2c, 0x52, 0x9e, 0x08, 0x24, 0x13, 0x80, 0xea, 0xf9, 0xc2, 0xd4, 0x6c, 0xdd, 0x19, 0x8c,
	0xef, 0xdc, 0xfd, 0x00, 0xdc, 0xfa, 0xc2, 0x01, 0x46, 0xdf, 0x81, 0xe1, 0x71, 0x71, 0x69, 0xe9,
	0xf7, 0xf0, 0xf4, 0x3f, 0xba, 0xac, 0x7d, 0x0f, 0x3d, 0x21, 0x99, 0xcc, 0x44, 0xc9, 0x97, 0x7f,
	0xf9, 0xc3, 0xbc, 0xec, 0x52, 0x75, 0x17, 0x8c, 0x26, 0x7c, 0x46, 0xdc, 0x85, 0xfb, 0x29, 0xc6,
	0x28, 0xf1, 0x42, 0xfd, 0x0f, 0xf0, 0xec, 0x01, 0x7f, 0xa6, 0xc4, 0x2b, 0xb8, 0xa9, 0xe0, 0x45,
	0xee, 0x6b, 0xbe, 0x39, 0x21, 0x93, 0x4c, 0x71, 0x8f, 0x7d, 0x75, 0xa6, 0x1f, 0xe1, 0xf9, 0xb7,
	0x34, 0xe6, 0x2c, 0x6c, 0xb2, 0xe7, 0xd4, 0xc7, 0x7f, 0x74, 0x80, 0xea, 0x8a, 0x20, 0x33, 0xd0,
	0xe7, 0x28, 0xc9, 0xb0, 0xf6, 0xac, 0x65, 0x29, 0xac, 0x17, 0xc7, 0xd2, 0x45, 0x31, 0xda, 0x21,
	0x0b, 0xe8, 0xe6, 0x2e, 0x91, 0x03, 0xb2, 0xcd, 0x63, 0x6b, 0x74, 0x34, 0x5f, 0x49, 0xcd, 0x40,
	0xf7, 0xb2, 0x46, 0x4b, 0x2d, 0x76, 0x1e, 0xb6, 0xd4, 0x66, 0x20, 0xed, 0x90, 0x2f, 0xd0, 0x2b,
	0x46, 0x4f, 0xec, 0x9a, 0x6d, 0x37, 0xcf, 0x7a, 0x79, 0x82, 0xa8, 0x04, 0xbf, 0xc2, 0xa0, 0x18,
	0x79, 0xe1, 0x8a, 0xd9, 0xb2, 0xe7, 0x2a, 0x63, 0xbd, 0xae, 0x33, 0xa7, 0x3c, 0xa2, 0x1d, 0x47,
	0x5b, 0xf5, 0x14, 0x3a, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0x45, 0x76, 0xd6, 0xd0, 0x47, 0x04,
	0x00, 0x00,
}
