// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vegetable.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vegetable struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fee                  int64    `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	IsChemical           bool     `protobuf:"varint,3,opt,name=is_chemical,json=isChemical,proto3" json:"is_chemical,omitempty"`
	ImagePath            string   `protobuf:"bytes,4,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	ProductionDate       string   `protobuf:"bytes,5,opt,name=production_date,json=productionDate,proto3" json:"production_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vegetable) Reset()         { *m = Vegetable{} }
func (m *Vegetable) String() string { return proto.CompactTextString(m) }
func (*Vegetable) ProtoMessage()    {}
func (*Vegetable) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{0}
}

func (m *Vegetable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vegetable.Unmarshal(m, b)
}
func (m *Vegetable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vegetable.Marshal(b, m, deterministic)
}
func (m *Vegetable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vegetable.Merge(m, src)
}
func (m *Vegetable) XXX_Size() int {
	return xxx_messageInfo_Vegetable.Size(m)
}
func (m *Vegetable) XXX_DiscardUnknown() {
	xxx_messageInfo_Vegetable.DiscardUnknown(m)
}

var xxx_messageInfo_Vegetable proto.InternalMessageInfo

func (m *Vegetable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vegetable) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Vegetable) GetIsChemical() bool {
	if m != nil {
		return m.IsChemical
	}
	return false
}

func (m *Vegetable) GetImagePath() string {
	if m != nil {
		return m.ImagePath
	}
	return ""
}

func (m *Vegetable) GetProductionDate() string {
	if m != nil {
		return m.ProductionDate
	}
	return ""
}

// Get
type GetMyVegetablesRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMyVegetablesRequest) Reset()         { *m = GetMyVegetablesRequest{} }
func (m *GetMyVegetablesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMyVegetablesRequest) ProtoMessage()    {}
func (*GetMyVegetablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{1}
}

func (m *GetMyVegetablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyVegetablesRequest.Unmarshal(m, b)
}
func (m *GetMyVegetablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyVegetablesRequest.Marshal(b, m, deterministic)
}
func (m *GetMyVegetablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyVegetablesRequest.Merge(m, src)
}
func (m *GetMyVegetablesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMyVegetablesRequest.Size(m)
}
func (m *GetMyVegetablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyVegetablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyVegetablesRequest proto.InternalMessageInfo

func (m *GetMyVegetablesRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetMyVegetablesResponse struct {
	Status               int64        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Vegetables           []*Vegetable `protobuf:"bytes,2,rep,name=vegetables,proto3" json:"vegetables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetMyVegetablesResponse) Reset()         { *m = GetMyVegetablesResponse{} }
func (m *GetMyVegetablesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMyVegetablesResponse) ProtoMessage()    {}
func (*GetMyVegetablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{2}
}

func (m *GetMyVegetablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyVegetablesResponse.Unmarshal(m, b)
}
func (m *GetMyVegetablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyVegetablesResponse.Marshal(b, m, deterministic)
}
func (m *GetMyVegetablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyVegetablesResponse.Merge(m, src)
}
func (m *GetMyVegetablesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMyVegetablesResponse.Size(m)
}
func (m *GetMyVegetablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyVegetablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyVegetablesResponse proto.InternalMessageInfo

func (m *GetMyVegetablesResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetMyVegetablesResponse) GetVegetables() []*Vegetable {
	if m != nil {
		return m.Vegetables
	}
	return nil
}

type VegetablesEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VegetablesEmpty) Reset()         { *m = VegetablesEmpty{} }
func (m *VegetablesEmpty) String() string { return proto.CompactTextString(m) }
func (*VegetablesEmpty) ProtoMessage()    {}
func (*VegetablesEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{3}
}

func (m *VegetablesEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VegetablesEmpty.Unmarshal(m, b)
}
func (m *VegetablesEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VegetablesEmpty.Marshal(b, m, deterministic)
}
func (m *VegetablesEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VegetablesEmpty.Merge(m, src)
}
func (m *VegetablesEmpty) XXX_Size() int {
	return xxx_messageInfo_VegetablesEmpty.Size(m)
}
func (m *VegetablesEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_VegetablesEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_VegetablesEmpty proto.InternalMessageInfo

type GetAllVegetablesResponse struct {
	Vegetables           []*Vegetable `protobuf:"bytes,1,rep,name=vegetables,proto3" json:"vegetables,omitempty"`
	Status               int64        `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetAllVegetablesResponse) Reset()         { *m = GetAllVegetablesResponse{} }
func (m *GetAllVegetablesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllVegetablesResponse) ProtoMessage()    {}
func (*GetAllVegetablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{4}
}

func (m *GetAllVegetablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllVegetablesResponse.Unmarshal(m, b)
}
func (m *GetAllVegetablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllVegetablesResponse.Marshal(b, m, deterministic)
}
func (m *GetAllVegetablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllVegetablesResponse.Merge(m, src)
}
func (m *GetAllVegetablesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllVegetablesResponse.Size(m)
}
func (m *GetAllVegetablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllVegetablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllVegetablesResponse proto.InternalMessageInfo

func (m *GetAllVegetablesResponse) GetVegetables() []*Vegetable {
	if m != nil {
		return m.Vegetables
	}
	return nil
}

func (m *GetAllVegetablesResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

// Create
type VegetableImage struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VegetableImage) Reset()         { *m = VegetableImage{} }
func (m *VegetableImage) String() string { return proto.CompactTextString(m) }
func (*VegetableImage) ProtoMessage()    {}
func (*VegetableImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{5}
}

func (m *VegetableImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VegetableImage.Unmarshal(m, b)
}
func (m *VegetableImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VegetableImage.Marshal(b, m, deterministic)
}
func (m *VegetableImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VegetableImage.Merge(m, src)
}
func (m *VegetableImage) XXX_Size() int {
	return xxx_messageInfo_VegetableImage.Size(m)
}
func (m *VegetableImage) XXX_DiscardUnknown() {
	xxx_messageInfo_VegetableImage.DiscardUnknown(m)
}

var xxx_messageInfo_VegetableImage proto.InternalMessageInfo

func (m *VegetableImage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PostMyVegetableRequest struct {
	Token                string          `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Vegetable            *Vegetable      `protobuf:"bytes,2,opt,name=vegetable,proto3" json:"vegetable,omitempty"`
	Image                *VegetableImage `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PostMyVegetableRequest) Reset()         { *m = PostMyVegetableRequest{} }
func (m *PostMyVegetableRequest) String() string { return proto.CompactTextString(m) }
func (*PostMyVegetableRequest) ProtoMessage()    {}
func (*PostMyVegetableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{6}
}

func (m *PostMyVegetableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMyVegetableRequest.Unmarshal(m, b)
}
func (m *PostMyVegetableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMyVegetableRequest.Marshal(b, m, deterministic)
}
func (m *PostMyVegetableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMyVegetableRequest.Merge(m, src)
}
func (m *PostMyVegetableRequest) XXX_Size() int {
	return xxx_messageInfo_PostMyVegetableRequest.Size(m)
}
func (m *PostMyVegetableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMyVegetableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostMyVegetableRequest proto.InternalMessageInfo

func (m *PostMyVegetableRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PostMyVegetableRequest) GetVegetable() *Vegetable {
	if m != nil {
		return m.Vegetable
	}
	return nil
}

func (m *PostMyVegetableRequest) GetImage() *VegetableImage {
	if m != nil {
		return m.Image
	}
	return nil
}

type PostMyVegetableResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostMyVegetableResponse) Reset()         { *m = PostMyVegetableResponse{} }
func (m *PostMyVegetableResponse) String() string { return proto.CompactTextString(m) }
func (*PostMyVegetableResponse) ProtoMessage()    {}
func (*PostMyVegetableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{7}
}

func (m *PostMyVegetableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMyVegetableResponse.Unmarshal(m, b)
}
func (m *PostMyVegetableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMyVegetableResponse.Marshal(b, m, deterministic)
}
func (m *PostMyVegetableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMyVegetableResponse.Merge(m, src)
}
func (m *PostMyVegetableResponse) XXX_Size() int {
	return xxx_messageInfo_PostMyVegetableResponse.Size(m)
}
func (m *PostMyVegetableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMyVegetableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostMyVegetableResponse proto.InternalMessageInfo

func (m *PostMyVegetableResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

// Update
type PutMyVegetableRequest struct {
	Token                string     `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Vegetable            *Vegetable `protobuf:"bytes,2,opt,name=vegetable,proto3" json:"vegetable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutMyVegetableRequest) Reset()         { *m = PutMyVegetableRequest{} }
func (m *PutMyVegetableRequest) String() string { return proto.CompactTextString(m) }
func (*PutMyVegetableRequest) ProtoMessage()    {}
func (*PutMyVegetableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{8}
}

func (m *PutMyVegetableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMyVegetableRequest.Unmarshal(m, b)
}
func (m *PutMyVegetableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMyVegetableRequest.Marshal(b, m, deterministic)
}
func (m *PutMyVegetableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMyVegetableRequest.Merge(m, src)
}
func (m *PutMyVegetableRequest) XXX_Size() int {
	return xxx_messageInfo_PutMyVegetableRequest.Size(m)
}
func (m *PutMyVegetableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMyVegetableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutMyVegetableRequest proto.InternalMessageInfo

func (m *PutMyVegetableRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PutMyVegetableRequest) GetVegetable() *Vegetable {
	if m != nil {
		return m.Vegetable
	}
	return nil
}

type PutMyVegetableResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutMyVegetableResponse) Reset()         { *m = PutMyVegetableResponse{} }
func (m *PutMyVegetableResponse) String() string { return proto.CompactTextString(m) }
func (*PutMyVegetableResponse) ProtoMessage()    {}
func (*PutMyVegetableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{9}
}

func (m *PutMyVegetableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMyVegetableResponse.Unmarshal(m, b)
}
func (m *PutMyVegetableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMyVegetableResponse.Marshal(b, m, deterministic)
}
func (m *PutMyVegetableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMyVegetableResponse.Merge(m, src)
}
func (m *PutMyVegetableResponse) XXX_Size() int {
	return xxx_messageInfo_PutMyVegetableResponse.Size(m)
}
func (m *PutMyVegetableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMyVegetableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutMyVegetableResponse proto.InternalMessageInfo

func (m *PutMyVegetableResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

// Delete
type DeleteMyVegetableRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	VegetableId          int64    `protobuf:"varint,2,opt,name=vegetable_id,json=vegetableId,proto3" json:"vegetable_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMyVegetableRequest) Reset()         { *m = DeleteMyVegetableRequest{} }
func (m *DeleteMyVegetableRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMyVegetableRequest) ProtoMessage()    {}
func (*DeleteMyVegetableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{10}
}

func (m *DeleteMyVegetableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMyVegetableRequest.Unmarshal(m, b)
}
func (m *DeleteMyVegetableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMyVegetableRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMyVegetableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMyVegetableRequest.Merge(m, src)
}
func (m *DeleteMyVegetableRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMyVegetableRequest.Size(m)
}
func (m *DeleteMyVegetableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMyVegetableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMyVegetableRequest proto.InternalMessageInfo

func (m *DeleteMyVegetableRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeleteMyVegetableRequest) GetVegetableId() int64 {
	if m != nil {
		return m.VegetableId
	}
	return 0
}

type DeleteMyVegetableResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMyVegetableResponse) Reset()         { *m = DeleteMyVegetableResponse{} }
func (m *DeleteMyVegetableResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMyVegetableResponse) ProtoMessage()    {}
func (*DeleteMyVegetableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50c7ebee713ee9ad, []int{11}
}

func (m *DeleteMyVegetableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMyVegetableResponse.Unmarshal(m, b)
}
func (m *DeleteMyVegetableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMyVegetableResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMyVegetableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMyVegetableResponse.Merge(m, src)
}
func (m *DeleteMyVegetableResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMyVegetableResponse.Size(m)
}
func (m *DeleteMyVegetableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMyVegetableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMyVegetableResponse proto.InternalMessageInfo

func (m *DeleteMyVegetableResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*Vegetable)(nil), "protocol.Vegetable")
	proto.RegisterType((*GetMyVegetablesRequest)(nil), "protocol.GetMyVegetablesRequest")
	proto.RegisterType((*GetMyVegetablesResponse)(nil), "protocol.GetMyVegetablesResponse")
	proto.RegisterType((*VegetablesEmpty)(nil), "protocol.VegetablesEmpty")
	proto.RegisterType((*GetAllVegetablesResponse)(nil), "protocol.GetAllVegetablesResponse")
	proto.RegisterType((*VegetableImage)(nil), "protocol.VegetableImage")
	proto.RegisterType((*PostMyVegetableRequest)(nil), "protocol.PostMyVegetableRequest")
	proto.RegisterType((*PostMyVegetableResponse)(nil), "protocol.PostMyVegetableResponse")
	proto.RegisterType((*PutMyVegetableRequest)(nil), "protocol.PutMyVegetableRequest")
	proto.RegisterType((*PutMyVegetableResponse)(nil), "protocol.PutMyVegetableResponse")
	proto.RegisterType((*DeleteMyVegetableRequest)(nil), "protocol.DeleteMyVegetableRequest")
	proto.RegisterType((*DeleteMyVegetableResponse)(nil), "protocol.DeleteMyVegetableResponse")
}

func init() { proto.RegisterFile("vegetable.proto", fileDescriptor_50c7ebee713ee9ad) }

var fileDescriptor_50c7ebee713ee9ad = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xd1, 0x6e, 0xda, 0x30,
	0x14, 0x25, 0x04, 0xaa, 0x72, 0xa9, 0xa0, 0xbd, 0x5d, 0x69, 0x8a, 0x34, 0x35, 0xf5, 0x26, 0x8d,
	0xa7, 0x68, 0x85, 0x2f, 0xd8, 0xd6, 0xa9, 0xea, 0xc3, 0x24, 0x14, 0xb4, 0x69, 0x0f, 0x53, 0x99,
	0x4b, 0x6e, 0x21, 0x5a, 0xc0, 0x59, 0xed, 0x4c, 0xea, 0x67, 0xec, 0x75, 0x5f, 0xb1, 0x4f, 0x9c,
	0x30, 0x90, 0x18, 0x08, 0x59, 0x1f, 0xb6, 0xa7, 0x38, 0xf6, 0xf1, 0x39, 0xc7, 0xf7, 0x9e, 0x0b,
	0xcd, 0x1f, 0x34, 0x26, 0xc5, 0xef, 0x22, 0xf2, 0xe2, 0x07, 0xa1, 0x04, 0xee, 0xeb, 0xcf, 0x48,
	0x44, 0xec, 0x97, 0x05, 0xb5, 0x4f, 0xab, 0x53, 0x44, 0xa8, 0xcc, 0xf8, 0x94, 0x1c, 0xcb, 0xb5,
	0x3a, 0x35, 0x5f, 0xaf, 0xf1, 0x10, 0xec, 0x7b, 0x22, 0xa7, 0xec, 0x5a, 0x1d, 0xdb, 0x9f, 0x2f,
	0xf1, 0x1c, 0xea, 0xa1, 0x1c, 0x8e, 0x26, 0x34, 0x0d, 0x47, 0x3c, 0x72, 0x6c, 0xd7, 0xea, 0xec,
	0xfb, 0x10, 0xca, 0x77, 0xcb, 0x1d, 0x7c, 0x0e, 0x10, 0x4e, 0xf9, 0x98, 0x86, 0x31, 0x57, 0x13,
	0xa7, 0xa2, 0xc9, 0x6a, 0x7a, 0xa7, 0xcf, 0xd5, 0x04, 0x5f, 0x41, 0x33, 0x7e, 0x10, 0x41, 0x32,
	0x52, 0xa1, 0x98, 0x0d, 0x03, 0xae, 0xc8, 0xa9, 0x6a, 0x4c, 0x23, 0xdb, 0xbe, 0xe2, 0x8a, 0x98,
	0x07, 0xad, 0x6b, 0x52, 0x1f, 0x1e, 0x53, 0x83, 0xd2, 0xa7, 0xef, 0x09, 0x49, 0x85, 0xcf, 0xa0,
	0xaa, 0xc4, 0x37, 0x9a, 0x2d, 0x9d, 0x2e, 0x7e, 0xd8, 0x3d, 0x9c, 0x6e, 0xe1, 0x65, 0x2c, 0x66,
	0x92, 0xb0, 0x05, 0x7b, 0x52, 0x71, 0x95, 0x48, 0x7d, 0xc3, 0xf6, 0x97, 0x7f, 0xd8, 0x03, 0x48,
	0x8b, 0x23, 0x9d, 0xb2, 0x6b, 0x77, 0xea, 0xdd, 0x63, 0x6f, 0x55, 0x1e, 0x2f, 0x65, 0xf2, 0x0d,
	0x18, 0x3b, 0x82, 0x66, 0x26, 0xf1, 0x7e, 0x1a, 0xab, 0x47, 0x36, 0x06, 0xe7, 0x9a, 0xd4, 0x9b,
	0x28, 0xca, 0xd1, 0x5e, 0xd7, 0xb0, 0x9e, 0xa4, 0x61, 0x18, 0x2e, 0x9b, 0x86, 0xd9, 0x4b, 0x68,
	0xa4, 0x17, 0x6e, 0xe6, 0x25, 0x9d, 0x37, 0x2d, 0xe0, 0x8a, 0xeb, 0x87, 0x1d, 0xf8, 0x7a, 0xcd,
	0x7e, 0x5a, 0xd0, 0xea, 0x0b, 0x69, 0xd6, 0xa2, 0xb0, 0x74, 0x78, 0x09, 0xb5, 0x54, 0x5c, 0x2b,
	0xee, 0xb0, 0x98, 0xa1, 0xd0, 0x83, 0xaa, 0xee, 0xa9, 0x0e, 0x40, 0xbd, 0xeb, 0xe4, 0xc0, 0xb5,
	0x41, 0x7f, 0x01, 0x63, 0x97, 0x70, 0xba, 0x65, 0xa9, 0xb8, 0x3b, 0xec, 0x2b, 0x9c, 0xf4, 0x93,
	0xff, 0xf9, 0x08, 0xf6, 0x1a, 0x5a, 0x9b, 0x0a, 0x7f, 0xf1, 0x34, 0x00, 0xe7, 0x8a, 0x22, 0x52,
	0xf4, 0x64, 0x5b, 0x17, 0x70, 0x90, 0x0a, 0x0e, 0xc3, 0x60, 0xd9, 0xd0, 0x7a, 0xba, 0x77, 0x13,
	0xb0, 0x1e, 0x9c, 0xe5, 0x90, 0x16, 0x3b, 0xe9, 0xfe, 0xae, 0x00, 0x64, 0x71, 0xc3, 0x5b, 0x38,
	0xd1, 0xe9, 0x7f, 0x2b, 0x92, 0xf1, 0x44, 0x19, 0x07, 0x6e, 0x56, 0x83, 0xfc, 0x71, 0x6a, 0x5f,
	0x14, 0x20, 0x16, 0x26, 0x58, 0x09, 0xbf, 0xc0, 0xb1, 0x3e, 0x1c, 0x88, 0x28, 0xf8, 0xf7, 0xec,
	0x03, 0x38, 0xdc, 0x1c, 0x20, 0x3c, 0xcb, 0x69, 0xde, 0x62, 0xde, 0xda, 0x6c, 0x8d, 0x33, 0x77,
	0xee, 0x58, 0x09, 0x3f, 0x43, 0x73, 0x23, 0x72, 0xa6, 0xdd, 0xfc, 0x01, 0x31, 0xed, 0xee, 0xc8,
	0x2b, 0x2b, 0xe1, 0x47, 0x68, 0xac, 0xe7, 0x06, 0xcf, 0x8d, 0x6b, 0x79, 0x99, 0x6d, 0xbb, 0xbb,
	0x01, 0x29, 0xed, 0x2d, 0x1c, 0x6d, 0xe5, 0x00, 0x8d, 0xb7, 0xee, 0x4a, 0x5e, 0xfb, 0x45, 0x21,
	0x66, 0xc5, 0x7f, 0xb7, 0xa7, 0x51, 0xbd, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xbe, 0x8f,
	0xec, 0x12, 0x06, 0x00, 0x00,
}
