// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entry.proto

package entry

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignInRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{0}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type EntryResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryResponse) Reset()         { *m = EntryResponse{} }
func (m *EntryResponse) String() string { return proto.CompactTextString(m) }
func (*EntryResponse) ProtoMessage()    {}
func (*EntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{1}
}

func (m *EntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryResponse.Unmarshal(m, b)
}
func (m *EntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryResponse.Marshal(b, m, deterministic)
}
func (m *EntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryResponse.Merge(m, src)
}
func (m *EntryResponse) XXX_Size() int {
	return xxx_messageInfo_EntryResponse.Size(m)
}
func (m *EntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EntryResponse proto.InternalMessageInfo

func (m *EntryResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *EntryResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SignUpRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Birthday             string   `protobuf:"bytes,3,opt,name=birthday,proto3" json:"birthday,omitempty"`
	IsSaler              bool     `protobuf:"varint,4,opt,name=is_saler,json=isSaler,proto3" json:"is_saler,omitempty"`
	IsBuyer              bool     `protobuf:"varint,5,opt,name=is_buyer,json=isBuyer,proto3" json:"is_buyer,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{2}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpRequest) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *SignUpRequest) GetIsSaler() bool {
	if m != nil {
		return m.IsSaler
	}
	return false
}

func (m *SignUpRequest) GetIsBuyer() bool {
	if m != nil {
		return m.IsBuyer
	}
	return false
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*SignInRequest)(nil), "entry.SignInRequest")
	proto.RegisterType((*EntryResponse)(nil), "entry.EntryResponse")
	proto.RegisterType((*SignUpRequest)(nil), "entry.SignUpRequest")
}

func init() { proto.RegisterFile("entry.proto", fileDescriptor_daa6c5b6c627940f) }

var fileDescriptor_daa6c5b6c627940f = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x49, 0xff, 0x84, 0x62, 0xd4, 0xc5, 0xaa, 0x50, 0xe8, 0x54, 0x65, 0xea, 0x92, 0x06,
	0x8a, 0x84, 0x58, 0x18, 0x5a, 0x89, 0x81, 0x35, 0x51, 0x17, 0x16, 0xe4, 0xb4, 0x47, 0x6b, 0xb5,
	0xb1, 0xc3, 0x9d, 0x03, 0xf4, 0x13, 0xf1, 0x35, 0x51, 0xec, 0xa4, 0x28, 0x48, 0x6c, 0xf9, 0xdd,
	0xe9, 0x5e, 0xde, 0x7b, 0x32, 0xbb, 0x04, 0x65, 0xf0, 0x38, 0x2b, 0x50, 0x1b, 0xcd, 0xfb, 0x16,
	0xc2, 0x05, 0x1b, 0xa6, 0x72, 0xab, 0x9e, 0x55, 0x02, 0xef, 0x25, 0x90, 0xe1, 0x23, 0xd6, 0x87,
	0x5c, 0xc8, 0x43, 0xe0, 0x4d, 0xbc, 0xe9, 0x45, 0xe2, 0x80, 0x8f, 0xd9, 0xa0, 0x10, 0x44, 0x9f,
	0x1a, 0x37, 0x41, 0xc7, 0x2e, 0x4e, 0x1c, 0x3e, 0xb2, 0xe1, 0x53, 0xa5, 0x95, 0x00, 0x15, 0x5a,
	0x11, 0xf0, 0x2b, 0xe6, 0x93, 0x11, 0xa6, 0x24, 0xab, 0xd1, 0x4d, 0x6a, 0xaa, 0xa4, 0x8d, 0xde,
	0x83, 0xaa, 0x15, 0x1c, 0x84, 0xdf, 0x9e, 0xb3, 0xb0, 0x2a, 0x1a, 0x0b, 0x9c, 0xf5, 0x94, 0xc8,
	0xa1, 0x76, 0x60, 0xbf, 0x7f, 0x6d, 0x75, 0xfe, 0xd8, 0xca, 0x24, 0x9a, 0xdd, 0x46, 0x1c, 0x83,
	0xae, 0xb3, 0xd5, 0x30, 0xbf, 0x66, 0x03, 0x49, 0xaf, 0x24, 0x0e, 0x80, 0x41, 0x6f, 0xe2, 0x4d,
	0x07, 0xc9, 0xb9, 0xa4, 0xb4, 0xc2, 0x7a, 0x95, 0x95, 0x47, 0xc0, 0xa0, 0xdf, 0xac, 0x96, 0x15,
	0xb6, 0x82, 0xfa, 0xed, 0xa0, 0xf3, 0x2f, 0xe6, 0xdb, 0xa0, 0xc4, 0xef, 0x99, 0xef, 0x5a, 0xe3,
	0xa3, 0x99, 0x2b, 0xb5, 0x55, 0xe2, 0xb8, 0x99, 0xb6, 0x7a, 0x09, 0xcf, 0x9a, 0xbb, 0x55, 0xd1,
	0xba, 0x3b, 0x25, 0xff, 0xef, 0x6e, 0xb9, 0x7a, 0x49, 0xb7, 0xd2, 0xec, 0xca, 0x6c, 0xb6, 0xd6,
	0x79, 0x3c, 0xbf, 0xb9, 0x7d, 0x88, 0x72, 0x89, 0x42, 0xee, 0x41, 0x1a, 0x21, 0x23, 0x8d, 0xdb,
	0x38, 0x11, 0xfb, 0xb2, 0x0a, 0x1b, 0x2d, 0x94, 0x36, 0x3b, 0xc0, 0x28, 0x05, 0xfc, 0x00, 0x8c,
	0xa5, 0x32, 0x80, 0x6f, 0x62, 0x0d, 0x14, 0x93, 0x9b, 0x60, 0xb1, 0x8e, 0xed, 0x6f, 0x32, 0xdf,
	0x3e, 0x85, 0xbb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x96, 0x91, 0xcb, 0x82, 0x19, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EntrysClient is the client API for Entrys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EntrysClient interface {
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*EntryResponse, error)
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*EntryResponse, error)
}

type entrysClient struct {
	cc *grpc.ClientConn
}

func NewEntrysClient(cc *grpc.ClientConn) EntrysClient {
	return &entrysClient{cc}
}

func (c *entrysClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*EntryResponse, error) {
	out := new(EntryResponse)
	err := c.cc.Invoke(ctx, "/entry.Entrys/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entrysClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*EntryResponse, error) {
	out := new(EntryResponse)
	err := c.cc.Invoke(ctx, "/entry.Entrys/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntrysServer is the server API for Entrys service.
type EntrysServer interface {
	SignIn(context.Context, *SignInRequest) (*EntryResponse, error)
	SignUp(context.Context, *SignUpRequest) (*EntryResponse, error)
}

func RegisterEntrysServer(s *grpc.Server, srv EntrysServer) {
	s.RegisterService(&_Entrys_serviceDesc, srv)
}

func _Entrys_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntrysServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entry.Entrys/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntrysServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Entrys_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntrysServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entry.Entrys/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntrysServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Entrys_serviceDesc = grpc.ServiceDesc{
	ServiceName: "entry.Entrys",
	HandlerType: (*EntrysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _Entrys_SignIn_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _Entrys_SignUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entry.proto",
}
