apiVersion: v1
kind: Service
metadata:
  labels: 
    name: rakusale-grpc
  name: rakusale-service
spec:
  clusterIP: None
  ports:
    - name: rakusale-grpc
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: rakusale-grpc