// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vegetable.proto

package vegetable // import "github.com/2018-miraikeitai-org/Rakusale-Another-Server/interfaces/server/rpc/vegetable"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VegetableType int32

const (
	VegetableType_SQUASH      VegetableType = 0
	VegetableType_CABBAGE     VegetableType = 1
	VegetableType_CUCUMBER    VegetableType = 2
	VegetableType_SWEETPOTATO VegetableType = 3
	VegetableType_POTATO      VegetableType = 4
	VegetableType_RADISH      VegetableType = 5
	VegetableType_ONION       VegetableType = 6
	VegetableType_CARROT      VegetableType = 7
	VegetableType_BELLPEPPER  VegetableType = 8
	VegetableType_SPINACH     VegetableType = 9
	VegetableType_LETTUCE     VegetableType = 10
)

var VegetableType_name = map[int32]string{
	0:  "SQUASH",
	1:  "CABBAGE",
	2:  "CUCUMBER",
	3:  "SWEETPOTATO",
	4:  "POTATO",
	5:  "RADISH",
	6:  "ONION",
	7:  "CARROT",
	8:  "BELLPEPPER",
	9:  "SPINACH",
	10: "LETTUCE",
}
var VegetableType_value = map[string]int32{
	"SQUASH":      0,
	"CABBAGE":     1,
	"CUCUMBER":    2,
	"SWEETPOTATO": 3,
	"POTATO":      4,
	"RADISH":      5,
	"ONION":       6,
	"CARROT":      7,
	"BELLPEPPER":  8,
	"SPINACH":     9,
	"LETTUCE":     10,
}

func (x VegetableType) String() string {
	return proto.EnumName(VegetableType_name, int32(x))
}
func (VegetableType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{0}
}

type RequestVegetable struct {
	Fee                  int64         `protobuf:"varint,1,opt,name=fee,proto3" json:"fee,omitempty"`
	IsChemical           bool          `protobuf:"varint,2,opt,name=isChemical,proto3" json:"isChemical,omitempty"`
	ProductionDate       string        `protobuf:"bytes,3,opt,name=productionDate,proto3" json:"productionDate,omitempty"`
	Introduction         string        `protobuf:"bytes,4,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Category             VegetableType `protobuf:"varint,5,opt,name=category,proto3,enum=vegetable.VegetableType" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RequestVegetable) Reset()         { *m = RequestVegetable{} }
func (m *RequestVegetable) String() string { return proto.CompactTextString(m) }
func (*RequestVegetable) ProtoMessage()    {}
func (*RequestVegetable) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{0}
}
func (m *RequestVegetable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVegetable.Unmarshal(m, b)
}
func (m *RequestVegetable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVegetable.Marshal(b, m, deterministic)
}
func (dst *RequestVegetable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVegetable.Merge(dst, src)
}
func (m *RequestVegetable) XXX_Size() int {
	return xxx_messageInfo_RequestVegetable.Size(m)
}
func (m *RequestVegetable) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVegetable.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVegetable proto.InternalMessageInfo

func (m *RequestVegetable) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *RequestVegetable) GetIsChemical() bool {
	if m != nil {
		return m.IsChemical
	}
	return false
}

func (m *RequestVegetable) GetProductionDate() string {
	if m != nil {
		return m.ProductionDate
	}
	return ""
}

func (m *RequestVegetable) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *RequestVegetable) GetCategory() VegetableType {
	if m != nil {
		return m.Category
	}
	return VegetableType_SQUASH
}

type ResponseVegetable struct {
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Fee                  int64         `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
	IsChemical           bool          `protobuf:"varint,4,opt,name=isChemical,proto3" json:"isChemical,omitempty"`
	ImagePath            string        `protobuf:"bytes,5,opt,name=imagePath,proto3" json:"imagePath,omitempty"`
	ProductionDate       string        `protobuf:"bytes,6,opt,name=productionDate,proto3" json:"productionDate,omitempty"`
	Category             VegetableType `protobuf:"varint,7,opt,name=category,proto3,enum=vegetable.VegetableType" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResponseVegetable) Reset()         { *m = ResponseVegetable{} }
func (m *ResponseVegetable) String() string { return proto.CompactTextString(m) }
func (*ResponseVegetable) ProtoMessage()    {}
func (*ResponseVegetable) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{1}
}
func (m *ResponseVegetable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseVegetable.Unmarshal(m, b)
}
func (m *ResponseVegetable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseVegetable.Marshal(b, m, deterministic)
}
func (dst *ResponseVegetable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseVegetable.Merge(dst, src)
}
func (m *ResponseVegetable) XXX_Size() int {
	return xxx_messageInfo_ResponseVegetable.Size(m)
}
func (m *ResponseVegetable) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseVegetable.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseVegetable proto.InternalMessageInfo

func (m *ResponseVegetable) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResponseVegetable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResponseVegetable) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *ResponseVegetable) GetIsChemical() bool {
	if m != nil {
		return m.IsChemical
	}
	return false
}

func (m *ResponseVegetable) GetImagePath() string {
	if m != nil {
		return m.ImagePath
	}
	return ""
}

func (m *ResponseVegetable) GetProductionDate() string {
	if m != nil {
		return m.ProductionDate
	}
	return ""
}

func (m *ResponseVegetable) GetCategory() VegetableType {
	if m != nil {
		return m.Category
	}
	return VegetableType_SQUASH
}

type ResponseShopVegetable struct {
	Amount               int64         `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Fee                  int64         `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
	IsChemical           bool          `protobuf:"varint,4,opt,name=isChemical,proto3" json:"isChemical,omitempty"`
	ImagePath            string        `protobuf:"bytes,5,opt,name=imagePath,proto3" json:"imagePath,omitempty"`
	ProductionDate       string        `protobuf:"bytes,6,opt,name=productionDate,proto3" json:"productionDate,omitempty"`
	Category             VegetableType `protobuf:"varint,7,opt,name=category,proto3,enum=vegetable.VegetableType" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResponseShopVegetable) Reset()         { *m = ResponseShopVegetable{} }
func (m *ResponseShopVegetable) String() string { return proto.CompactTextString(m) }
func (*ResponseShopVegetable) ProtoMessage()    {}
func (*ResponseShopVegetable) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{2}
}
func (m *ResponseShopVegetable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseShopVegetable.Unmarshal(m, b)
}
func (m *ResponseShopVegetable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseShopVegetable.Marshal(b, m, deterministic)
}
func (dst *ResponseShopVegetable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseShopVegetable.Merge(dst, src)
}
func (m *ResponseShopVegetable) XXX_Size() int {
	return xxx_messageInfo_ResponseShopVegetable.Size(m)
}
func (m *ResponseShopVegetable) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseShopVegetable.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseShopVegetable proto.InternalMessageInfo

func (m *ResponseShopVegetable) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ResponseShopVegetable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResponseShopVegetable) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *ResponseShopVegetable) GetIsChemical() bool {
	if m != nil {
		return m.IsChemical
	}
	return false
}

func (m *ResponseShopVegetable) GetImagePath() string {
	if m != nil {
		return m.ImagePath
	}
	return ""
}

func (m *ResponseShopVegetable) GetProductionDate() string {
	if m != nil {
		return m.ProductionDate
	}
	return ""
}

func (m *ResponseShopVegetable) GetCategory() VegetableType {
	if m != nil {
		return m.Category
	}
	return VegetableType_SQUASH
}

// Get
type GetMyVegetablesRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMyVegetablesRequest) Reset()         { *m = GetMyVegetablesRequest{} }
func (m *GetMyVegetablesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMyVegetablesRequest) ProtoMessage()    {}
func (*GetMyVegetablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{3}
}
func (m *GetMyVegetablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyVegetablesRequest.Unmarshal(m, b)
}
func (m *GetMyVegetablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyVegetablesRequest.Marshal(b, m, deterministic)
}
func (dst *GetMyVegetablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyVegetablesRequest.Merge(dst, src)
}
func (m *GetMyVegetablesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMyVegetablesRequest.Size(m)
}
func (m *GetMyVegetablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyVegetablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyVegetablesRequest proto.InternalMessageInfo

func (m *GetMyVegetablesRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetMyVegetablesResponse struct {
	Status               int64                `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Vegetables           []*ResponseVegetable `protobuf:"bytes,2,rep,name=vegetables,proto3" json:"vegetables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetMyVegetablesResponse) Reset()         { *m = GetMyVegetablesResponse{} }
func (m *GetMyVegetablesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMyVegetablesResponse) ProtoMessage()    {}
func (*GetMyVegetablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{4}
}
func (m *GetMyVegetablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyVegetablesResponse.Unmarshal(m, b)
}
func (m *GetMyVegetablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyVegetablesResponse.Marshal(b, m, deterministic)
}
func (dst *GetMyVegetablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyVegetablesResponse.Merge(dst, src)
}
func (m *GetMyVegetablesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMyVegetablesResponse.Size(m)
}
func (m *GetMyVegetablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyVegetablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyVegetablesResponse proto.InternalMessageInfo

func (m *GetMyVegetablesResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetMyVegetablesResponse) GetVegetables() []*ResponseVegetable {
	if m != nil {
		return m.Vegetables
	}
	return nil
}

type VegetablesEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VegetablesEmpty) Reset()         { *m = VegetablesEmpty{} }
func (m *VegetablesEmpty) String() string { return proto.CompactTextString(m) }
func (*VegetablesEmpty) ProtoMessage()    {}
func (*VegetablesEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{5}
}
func (m *VegetablesEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VegetablesEmpty.Unmarshal(m, b)
}
func (m *VegetablesEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VegetablesEmpty.Marshal(b, m, deterministic)
}
func (dst *VegetablesEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VegetablesEmpty.Merge(dst, src)
}
func (m *VegetablesEmpty) XXX_Size() int {
	return xxx_messageInfo_VegetablesEmpty.Size(m)
}
func (m *VegetablesEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_VegetablesEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_VegetablesEmpty proto.InternalMessageInfo

type GetAllVegetablesResponse struct {
	Vegetables           []*ResponseVegetable `protobuf:"bytes,1,rep,name=vegetables,proto3" json:"vegetables,omitempty"`
	Status               int64                `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetAllVegetablesResponse) Reset()         { *m = GetAllVegetablesResponse{} }
func (m *GetAllVegetablesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllVegetablesResponse) ProtoMessage()    {}
func (*GetAllVegetablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{6}
}
func (m *GetAllVegetablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllVegetablesResponse.Unmarshal(m, b)
}
func (m *GetAllVegetablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllVegetablesResponse.Marshal(b, m, deterministic)
}
func (dst *GetAllVegetablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllVegetablesResponse.Merge(dst, src)
}
func (m *GetAllVegetablesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllVegetablesResponse.Size(m)
}
func (m *GetAllVegetablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllVegetablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllVegetablesResponse proto.InternalMessageInfo

func (m *GetAllVegetablesResponse) GetVegetables() []*ResponseVegetable {
	if m != nil {
		return m.Vegetables
	}
	return nil
}

func (m *GetAllVegetablesResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type GetSingleShopAllVegetablesRequest struct {
	ShopId               int64    `protobuf:"varint,1,opt,name=shopId,proto3" json:"shopId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSingleShopAllVegetablesRequest) Reset()         { *m = GetSingleShopAllVegetablesRequest{} }
func (m *GetSingleShopAllVegetablesRequest) String() string { return proto.CompactTextString(m) }
func (*GetSingleShopAllVegetablesRequest) ProtoMessage()    {}
func (*GetSingleShopAllVegetablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{7}
}
func (m *GetSingleShopAllVegetablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSingleShopAllVegetablesRequest.Unmarshal(m, b)
}
func (m *GetSingleShopAllVegetablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSingleShopAllVegetablesRequest.Marshal(b, m, deterministic)
}
func (dst *GetSingleShopAllVegetablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSingleShopAllVegetablesRequest.Merge(dst, src)
}
func (m *GetSingleShopAllVegetablesRequest) XXX_Size() int {
	return xxx_messageInfo_GetSingleShopAllVegetablesRequest.Size(m)
}
func (m *GetSingleShopAllVegetablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSingleShopAllVegetablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSingleShopAllVegetablesRequest proto.InternalMessageInfo

func (m *GetSingleShopAllVegetablesRequest) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type GetSingleShopAllVegetablesResponse struct {
	Status               int64                    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Vegetables           []*ResponseShopVegetable `protobuf:"bytes,2,rep,name=vegetables,proto3" json:"vegetables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetSingleShopAllVegetablesResponse) Reset()         { *m = GetSingleShopAllVegetablesResponse{} }
func (m *GetSingleShopAllVegetablesResponse) String() string { return proto.CompactTextString(m) }
func (*GetSingleShopAllVegetablesResponse) ProtoMessage()    {}
func (*GetSingleShopAllVegetablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{8}
}
func (m *GetSingleShopAllVegetablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSingleShopAllVegetablesResponse.Unmarshal(m, b)
}
func (m *GetSingleShopAllVegetablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSingleShopAllVegetablesResponse.Marshal(b, m, deterministic)
}
func (dst *GetSingleShopAllVegetablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSingleShopAllVegetablesResponse.Merge(dst, src)
}
func (m *GetSingleShopAllVegetablesResponse) XXX_Size() int {
	return xxx_messageInfo_GetSingleShopAllVegetablesResponse.Size(m)
}
func (m *GetSingleShopAllVegetablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSingleShopAllVegetablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSingleShopAllVegetablesResponse proto.InternalMessageInfo

func (m *GetSingleShopAllVegetablesResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetSingleShopAllVegetablesResponse) GetVegetables() []*ResponseShopVegetable {
	if m != nil {
		return m.Vegetables
	}
	return nil
}

// Create
type VegetableImage struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VegetableImage) Reset()         { *m = VegetableImage{} }
func (m *VegetableImage) String() string { return proto.CompactTextString(m) }
func (*VegetableImage) ProtoMessage()    {}
func (*VegetableImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{9}
}
func (m *VegetableImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VegetableImage.Unmarshal(m, b)
}
func (m *VegetableImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VegetableImage.Marshal(b, m, deterministic)
}
func (dst *VegetableImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VegetableImage.Merge(dst, src)
}
func (m *VegetableImage) XXX_Size() int {
	return xxx_messageInfo_VegetableImage.Size(m)
}
func (m *VegetableImage) XXX_DiscardUnknown() {
	xxx_messageInfo_VegetableImage.DiscardUnknown(m)
}

var xxx_messageInfo_VegetableImage proto.InternalMessageInfo

func (m *VegetableImage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PostMyVegetableRequest struct {
	Token                string            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Vegetable            *RequestVegetable `protobuf:"bytes,2,opt,name=vegetable,proto3" json:"vegetable,omitempty"`
	Image                *VegetableImage   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PostMyVegetableRequest) Reset()         { *m = PostMyVegetableRequest{} }
func (m *PostMyVegetableRequest) String() string { return proto.CompactTextString(m) }
func (*PostMyVegetableRequest) ProtoMessage()    {}
func (*PostMyVegetableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{10}
}
func (m *PostMyVegetableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMyVegetableRequest.Unmarshal(m, b)
}
func (m *PostMyVegetableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMyVegetableRequest.Marshal(b, m, deterministic)
}
func (dst *PostMyVegetableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMyVegetableRequest.Merge(dst, src)
}
func (m *PostMyVegetableRequest) XXX_Size() int {
	return xxx_messageInfo_PostMyVegetableRequest.Size(m)
}
func (m *PostMyVegetableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMyVegetableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostMyVegetableRequest proto.InternalMessageInfo

func (m *PostMyVegetableRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PostMyVegetableRequest) GetVegetable() *RequestVegetable {
	if m != nil {
		return m.Vegetable
	}
	return nil
}

func (m *PostMyVegetableRequest) GetImage() *VegetableImage {
	if m != nil {
		return m.Image
	}
	return nil
}

type PostMyVegetableResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostMyVegetableResponse) Reset()         { *m = PostMyVegetableResponse{} }
func (m *PostMyVegetableResponse) String() string { return proto.CompactTextString(m) }
func (*PostMyVegetableResponse) ProtoMessage()    {}
func (*PostMyVegetableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{11}
}
func (m *PostMyVegetableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMyVegetableResponse.Unmarshal(m, b)
}
func (m *PostMyVegetableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMyVegetableResponse.Marshal(b, m, deterministic)
}
func (dst *PostMyVegetableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMyVegetableResponse.Merge(dst, src)
}
func (m *PostMyVegetableResponse) XXX_Size() int {
	return xxx_messageInfo_PostMyVegetableResponse.Size(m)
}
func (m *PostMyVegetableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMyVegetableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostMyVegetableResponse proto.InternalMessageInfo

func (m *PostMyVegetableResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

// Update
type PutMyVegetableRequest struct {
	Token                string            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	VId                  int64             `protobuf:"varint,2,opt,name=v_id,json=vId,proto3" json:"v_id,omitempty"`
	Vegetable            *RequestVegetable `protobuf:"bytes,3,opt,name=vegetable,proto3" json:"vegetable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PutMyVegetableRequest) Reset()         { *m = PutMyVegetableRequest{} }
func (m *PutMyVegetableRequest) String() string { return proto.CompactTextString(m) }
func (*PutMyVegetableRequest) ProtoMessage()    {}
func (*PutMyVegetableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{12}
}
func (m *PutMyVegetableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMyVegetableRequest.Unmarshal(m, b)
}
func (m *PutMyVegetableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMyVegetableRequest.Marshal(b, m, deterministic)
}
func (dst *PutMyVegetableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMyVegetableRequest.Merge(dst, src)
}
func (m *PutMyVegetableRequest) XXX_Size() int {
	return xxx_messageInfo_PutMyVegetableRequest.Size(m)
}
func (m *PutMyVegetableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMyVegetableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutMyVegetableRequest proto.InternalMessageInfo

func (m *PutMyVegetableRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PutMyVegetableRequest) GetVId() int64 {
	if m != nil {
		return m.VId
	}
	return 0
}

func (m *PutMyVegetableRequest) GetVegetable() *RequestVegetable {
	if m != nil {
		return m.Vegetable
	}
	return nil
}

type PutMyVegetableResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutMyVegetableResponse) Reset()         { *m = PutMyVegetableResponse{} }
func (m *PutMyVegetableResponse) String() string { return proto.CompactTextString(m) }
func (*PutMyVegetableResponse) ProtoMessage()    {}
func (*PutMyVegetableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{13}
}
func (m *PutMyVegetableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMyVegetableResponse.Unmarshal(m, b)
}
func (m *PutMyVegetableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMyVegetableResponse.Marshal(b, m, deterministic)
}
func (dst *PutMyVegetableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMyVegetableResponse.Merge(dst, src)
}
func (m *PutMyVegetableResponse) XXX_Size() int {
	return xxx_messageInfo_PutMyVegetableResponse.Size(m)
}
func (m *PutMyVegetableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMyVegetableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutMyVegetableResponse proto.InternalMessageInfo

func (m *PutMyVegetableResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

// Delete
type DeleteMyVegetableRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	VId                  int64    `protobuf:"varint,2,opt,name=v_id,json=vId,proto3" json:"v_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMyVegetableRequest) Reset()         { *m = DeleteMyVegetableRequest{} }
func (m *DeleteMyVegetableRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMyVegetableRequest) ProtoMessage()    {}
func (*DeleteMyVegetableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{14}
}
func (m *DeleteMyVegetableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMyVegetableRequest.Unmarshal(m, b)
}
func (m *DeleteMyVegetableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMyVegetableRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteMyVegetableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMyVegetableRequest.Merge(dst, src)
}
func (m *DeleteMyVegetableRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMyVegetableRequest.Size(m)
}
func (m *DeleteMyVegetableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMyVegetableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMyVegetableRequest proto.InternalMessageInfo

func (m *DeleteMyVegetableRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeleteMyVegetableRequest) GetVId() int64 {
	if m != nil {
		return m.VId
	}
	return 0
}

type DeleteMyVegetableResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMyVegetableResponse) Reset()         { *m = DeleteMyVegetableResponse{} }
func (m *DeleteMyVegetableResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMyVegetableResponse) ProtoMessage()    {}
func (*DeleteMyVegetableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_f8b98f3466bf10a1, []int{15}
}
func (m *DeleteMyVegetableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMyVegetableResponse.Unmarshal(m, b)
}
func (m *DeleteMyVegetableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMyVegetableResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteMyVegetableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMyVegetableResponse.Merge(dst, src)
}
func (m *DeleteMyVegetableResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMyVegetableResponse.Size(m)
}
func (m *DeleteMyVegetableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMyVegetableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMyVegetableResponse proto.InternalMessageInfo

func (m *DeleteMyVegetableResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestVegetable)(nil), "vegetable.RequestVegetable")
	proto.RegisterType((*ResponseVegetable)(nil), "vegetable.ResponseVegetable")
	proto.RegisterType((*ResponseShopVegetable)(nil), "vegetable.ResponseShopVegetable")
	proto.RegisterType((*GetMyVegetablesRequest)(nil), "vegetable.GetMyVegetablesRequest")
	proto.RegisterType((*GetMyVegetablesResponse)(nil), "vegetable.GetMyVegetablesResponse")
	proto.RegisterType((*VegetablesEmpty)(nil), "vegetable.VegetablesEmpty")
	proto.RegisterType((*GetAllVegetablesResponse)(nil), "vegetable.GetAllVegetablesResponse")
	proto.RegisterType((*GetSingleShopAllVegetablesRequest)(nil), "vegetable.GetSingleShopAllVegetablesRequest")
	proto.RegisterType((*GetSingleShopAllVegetablesResponse)(nil), "vegetable.GetSingleShopAllVegetablesResponse")
	proto.RegisterType((*VegetableImage)(nil), "vegetable.VegetableImage")
	proto.RegisterType((*PostMyVegetableRequest)(nil), "vegetable.PostMyVegetableRequest")
	proto.RegisterType((*PostMyVegetableResponse)(nil), "vegetable.PostMyVegetableResponse")
	proto.RegisterType((*PutMyVegetableRequest)(nil), "vegetable.PutMyVegetableRequest")
	proto.RegisterType((*PutMyVegetableResponse)(nil), "vegetable.PutMyVegetableResponse")
	proto.RegisterType((*DeleteMyVegetableRequest)(nil), "vegetable.DeleteMyVegetableRequest")
	proto.RegisterType((*DeleteMyVegetableResponse)(nil), "vegetable.DeleteMyVegetableResponse")
	proto.RegisterEnum("vegetable.VegetableType", VegetableType_name, VegetableType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VegetablesClient is the client API for Vegetables service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VegetablesClient interface {
	GetMyBoughtVegetables(ctx context.Context, in *GetMyVegetablesRequest, opts ...grpc.CallOption) (*GetMyVegetablesResponse, error)
	GetMySoldVegetables(ctx context.Context, in *GetMyVegetablesRequest, opts ...grpc.CallOption) (*GetMyVegetablesResponse, error)
	GetAllVegetables(ctx context.Context, in *VegetablesEmpty, opts ...grpc.CallOption) (*GetAllVegetablesResponse, error)
	GetSingleShopAllVegetables(ctx context.Context, in *GetSingleShopAllVegetablesRequest, opts ...grpc.CallOption) (*GetSingleShopAllVegetablesResponse, error)
	PostMyVegetable(ctx context.Context, in *PostMyVegetableRequest, opts ...grpc.CallOption) (*PostMyVegetableResponse, error)
	PutMyVegetable(ctx context.Context, in *PutMyVegetableRequest, opts ...grpc.CallOption) (*PutMyVegetableResponse, error)
	DeleteMyVegetable(ctx context.Context, in *DeleteMyVegetableRequest, opts ...grpc.CallOption) (*DeleteMyVegetableResponse, error)
}

type vegetablesClient struct {
	cc *grpc.ClientConn
}

func NewVegetablesClient(cc *grpc.ClientConn) VegetablesClient {
	return &vegetablesClient{cc}
}

func (c *vegetablesClient) GetMyBoughtVegetables(ctx context.Context, in *GetMyVegetablesRequest, opts ...grpc.CallOption) (*GetMyVegetablesResponse, error) {
	out := new(GetMyVegetablesResponse)
	err := c.cc.Invoke(ctx, "/vegetable.Vegetables/GetMyBoughtVegetables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vegetablesClient) GetMySoldVegetables(ctx context.Context, in *GetMyVegetablesRequest, opts ...grpc.CallOption) (*GetMyVegetablesResponse, error) {
	out := new(GetMyVegetablesResponse)
	err := c.cc.Invoke(ctx, "/vegetable.Vegetables/GetMySoldVegetables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vegetablesClient) GetAllVegetables(ctx context.Context, in *VegetablesEmpty, opts ...grpc.CallOption) (*GetAllVegetablesResponse, error) {
	out := new(GetAllVegetablesResponse)
	err := c.cc.Invoke(ctx, "/vegetable.Vegetables/GetAllVegetables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vegetablesClient) GetSingleShopAllVegetables(ctx context.Context, in *GetSingleShopAllVegetablesRequest, opts ...grpc.CallOption) (*GetSingleShopAllVegetablesResponse, error) {
	out := new(GetSingleShopAllVegetablesResponse)
	err := c.cc.Invoke(ctx, "/vegetable.Vegetables/GetSingleShopAllVegetables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vegetablesClient) PostMyVegetable(ctx context.Context, in *PostMyVegetableRequest, opts ...grpc.CallOption) (*PostMyVegetableResponse, error) {
	out := new(PostMyVegetableResponse)
	err := c.cc.Invoke(ctx, "/vegetable.Vegetables/PostMyVegetable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vegetablesClient) PutMyVegetable(ctx context.Context, in *PutMyVegetableRequest, opts ...grpc.CallOption) (*PutMyVegetableResponse, error) {
	out := new(PutMyVegetableResponse)
	err := c.cc.Invoke(ctx, "/vegetable.Vegetables/PutMyVegetable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vegetablesClient) DeleteMyVegetable(ctx context.Context, in *DeleteMyVegetableRequest, opts ...grpc.CallOption) (*DeleteMyVegetableResponse, error) {
	out := new(DeleteMyVegetableResponse)
	err := c.cc.Invoke(ctx, "/vegetable.Vegetables/DeleteMyVegetable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VegetablesServer is the server API for Vegetables service.
type VegetablesServer interface {
	GetMyBoughtVegetables(context.Context, *GetMyVegetablesRequest) (*GetMyVegetablesResponse, error)
	GetMySoldVegetables(context.Context, *GetMyVegetablesRequest) (*GetMyVegetablesResponse, error)
	GetAllVegetables(context.Context, *VegetablesEmpty) (*GetAllVegetablesResponse, error)
	GetSingleShopAllVegetables(context.Context, *GetSingleShopAllVegetablesRequest) (*GetSingleShopAllVegetablesResponse, error)
	PostMyVegetable(context.Context, *PostMyVegetableRequest) (*PostMyVegetableResponse, error)
	PutMyVegetable(context.Context, *PutMyVegetableRequest) (*PutMyVegetableResponse, error)
	DeleteMyVegetable(context.Context, *DeleteMyVegetableRequest) (*DeleteMyVegetableResponse, error)
}

func RegisterVegetablesServer(s *grpc.Server, srv VegetablesServer) {
	s.RegisterService(&_Vegetables_serviceDesc, srv)
}

func _Vegetables_GetMyBoughtVegetables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyVegetablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VegetablesServer).GetMyBoughtVegetables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vegetable.Vegetables/GetMyBoughtVegetables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VegetablesServer).GetMyBoughtVegetables(ctx, req.(*GetMyVegetablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vegetables_GetMySoldVegetables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyVegetablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VegetablesServer).GetMySoldVegetables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vegetable.Vegetables/GetMySoldVegetables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VegetablesServer).GetMySoldVegetables(ctx, req.(*GetMyVegetablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vegetables_GetAllVegetables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VegetablesEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VegetablesServer).GetAllVegetables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vegetable.Vegetables/GetAllVegetables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VegetablesServer).GetAllVegetables(ctx, req.(*VegetablesEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vegetables_GetSingleShopAllVegetables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSingleShopAllVegetablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VegetablesServer).GetSingleShopAllVegetables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vegetable.Vegetables/GetSingleShopAllVegetables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VegetablesServer).GetSingleShopAllVegetables(ctx, req.(*GetSingleShopAllVegetablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vegetables_PostMyVegetable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMyVegetableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VegetablesServer).PostMyVegetable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vegetable.Vegetables/PostMyVegetable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VegetablesServer).PostMyVegetable(ctx, req.(*PostMyVegetableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vegetables_PutMyVegetable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutMyVegetableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VegetablesServer).PutMyVegetable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vegetable.Vegetables/PutMyVegetable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VegetablesServer).PutMyVegetable(ctx, req.(*PutMyVegetableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vegetables_DeleteMyVegetable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMyVegetableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VegetablesServer).DeleteMyVegetable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vegetable.Vegetables/DeleteMyVegetable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VegetablesServer).DeleteMyVegetable(ctx, req.(*DeleteMyVegetableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Vegetables_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vegetable.Vegetables",
	HandlerType: (*VegetablesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyBoughtVegetables",
			Handler:    _Vegetables_GetMyBoughtVegetables_Handler,
		},
		{
			MethodName: "GetMySoldVegetables",
			Handler:    _Vegetables_GetMySoldVegetables_Handler,
		},
		{
			MethodName: "GetAllVegetables",
			Handler:    _Vegetables_GetAllVegetables_Handler,
		},
		{
			MethodName: "GetSingleShopAllVegetables",
			Handler:    _Vegetables_GetSingleShopAllVegetables_Handler,
		},
		{
			MethodName: "PostMyVegetable",
			Handler:    _Vegetables_PostMyVegetable_Handler,
		},
		{
			MethodName: "PutMyVegetable",
			Handler:    _Vegetables_PutMyVegetable_Handler,
		},
		{
			MethodName: "DeleteMyVegetable",
			Handler:    _Vegetables_DeleteMyVegetable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vegetable.proto",
}

func init() { proto.RegisterFile("vegetable.proto", fileDescriptor_vegetable_f8b98f3466bf10a1) }

var fileDescriptor_vegetable_f8b98f3466bf10a1 = []byte{
	// 882 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0xf3, 0xd7, 0xe6, 0xa4, 0xa4, 0xee, 0x40, 0xbb, 0xde, 0xb0, 0x42, 0xe9, 0xb0, 0x42,
	0x11, 0x22, 0xcd, 0x6e, 0x96, 0x0b, 0x10, 0x5c, 0xe0, 0xa4, 0x56, 0x1b, 0xa9, 0xdb, 0x84, 0x71,
	0x42, 0xc5, 0x5e, 0xc0, 0x4e, 0x93, 0xd9, 0xc4, 0x6a, 0xe2, 0x31, 0xf6, 0xa4, 0x52, 0xb5, 0x12,
	0x0f, 0xc2, 0x15, 0xaf, 0xc1, 0x0b, 0xf0, 0x26, 0x3c, 0x00, 0x6f, 0x80, 0x3c, 0x49, 0xfc, 0x93,
	0x38, 0xde, 0xae, 0x10, 0x37, 0xdc, 0xcd, 0x9c, 0x39, 0x9e, 0xef, 0x7c, 0xdf, 0x9c, 0xf3, 0xc9,
	0x70, 0x70, 0xc7, 0xc6, 0x4c, 0xd0, 0x9b, 0x29, 0x3b, 0x75, 0x5c, 0x2e, 0x38, 0x2a, 0x06, 0x01,
	0xfc, 0xa7, 0x02, 0x2a, 0x61, 0xbf, 0xcc, 0x99, 0x27, 0x7e, 0x58, 0x05, 0x91, 0x0a, 0xd9, 0x37,
	0x8c, 0x69, 0x4a, 0x55, 0xa9, 0x65, 0x89, 0xbf, 0x44, 0x9f, 0x00, 0x58, 0x5e, 0x7b, 0xc2, 0x66,
	0xd6, 0x90, 0x4e, 0xb5, 0x4c, 0x55, 0xa9, 0xed, 0x91, 0x48, 0x04, 0x7d, 0x06, 0x65, 0xc7, 0xe5,
	0xa3, 0xf9, 0x50, 0x58, 0xdc, 0x3e, 0xa3, 0x82, 0x69, 0xd9, 0xaa, 0x52, 0x2b, 0x92, 0xb5, 0x28,
	0xc2, 0xb0, 0x6f, 0xd9, 0x22, 0x88, 0x69, 0x39, 0x99, 0x15, 0x8b, 0xa1, 0x2f, 0x61, 0x6f, 0x48,
	0x05, 0x1b, 0x73, 0xf7, 0x5e, 0xcb, 0x57, 0x95, 0x5a, 0xb9, 0xa9, 0x9d, 0x86, 0x0c, 0x82, 0x2a,
	0xfb, 0xf7, 0x0e, 0x23, 0x41, 0x26, 0xfe, 0x4b, 0x81, 0x43, 0xc2, 0x3c, 0x87, 0xdb, 0x1e, 0x0b,
	0x99, 0x94, 0x21, 0x63, 0x8d, 0x96, 0x44, 0x32, 0xd6, 0x08, 0x21, 0xc8, 0xd9, 0x74, 0xc6, 0x24,
	0x83, 0x22, 0x91, 0xeb, 0x15, 0xdb, 0xec, 0x36, 0xb6, 0xb9, 0x0d, 0xb6, 0x4f, 0xa0, 0x68, 0xcd,
	0xe8, 0x98, 0xf5, 0xa8, 0x98, 0xc8, 0x12, 0x8b, 0x24, 0x0c, 0x24, 0x68, 0x51, 0x48, 0xd4, 0x22,
	0xca, 0x73, 0xf7, 0xc1, 0x3c, 0xff, 0x56, 0xe0, 0x68, 0xc5, 0xd3, 0x9c, 0x70, 0x27, 0xe4, 0x7a,
	0x0c, 0x05, 0x3a, 0xe3, 0x73, 0x5b, 0x2c, 0xf9, 0x2e, 0x77, 0xff, 0x03, 0xce, 0xa7, 0x70, 0x7c,
	0xce, 0xc4, 0xcb, 0xfb, 0xe0, 0xdc, 0x5b, 0xb6, 0x2c, 0xfa, 0x08, 0xf2, 0x82, 0xdf, 0x32, 0x5b,
	0x52, 0x2e, 0x92, 0xc5, 0x06, 0x73, 0x78, 0xb4, 0x91, 0xbf, 0x50, 0xcc, 0x17, 0xc9, 0x13, 0x54,
	0xcc, 0xbd, 0x95, 0x48, 0x8b, 0x1d, 0xfa, 0x16, 0x20, 0xa8, 0xc3, 0xd3, 0x32, 0xd5, 0x6c, 0xad,
	0xd4, 0x7c, 0x12, 0x29, 0x6d, 0xa3, 0xb5, 0x48, 0x24, 0x1f, 0x1f, 0xc2, 0x41, 0x88, 0x65, 0xcc,
	0x1c, 0x71, 0x8f, 0x1d, 0xd0, 0xce, 0x99, 0xd0, 0xa7, 0xd3, 0x84, 0x22, 0xe2, 0x60, 0xca, 0xfb,
	0x81, 0x45, 0x28, 0x64, 0xa2, 0x14, 0xf0, 0x37, 0x70, 0x72, 0xce, 0x84, 0x69, 0xd9, 0xe3, 0xa9,
	0xec, 0x8c, 0x35, 0xec, 0x85, 0x60, 0xfe, 0xc7, 0x13, 0xee, 0x74, 0x46, 0x01, 0x7f, 0xb9, 0xc3,
	0xbf, 0x02, 0x4e, 0xfb, 0xf8, 0x1d, 0xea, 0x7d, 0x97, 0xa0, 0x5e, 0x35, 0x81, 0x50, 0xac, 0x61,
	0x63, 0x0a, 0x3e, 0x85, 0x72, 0x70, 0xd0, 0xf1, 0xdb, 0xca, 0x6f, 0xdb, 0x11, 0x15, 0x54, 0x22,
	0xed, 0x13, 0xb9, 0xc6, 0xbf, 0x29, 0x70, 0xdc, 0xe3, 0x5e, 0xf4, 0x69, 0x53, 0x3b, 0x01, 0x7d,
	0x0d, 0xa1, 0xd7, 0x49, 0xb9, 0x4a, 0xcd, 0x8f, 0x63, 0x75, 0xc5, 0x9d, 0x8f, 0x84, 0xd9, 0xa8,
	0x01, 0x79, 0xd9, 0xdf, 0x72, 0x48, 0x4a, 0xcd, 0xc7, 0x49, 0x7d, 0x2a, 0x2b, 0x25, 0x8b, 0x3c,
	0xfc, 0x1c, 0x1e, 0x6d, 0xd4, 0x96, 0xae, 0x1b, 0x7e, 0x0b, 0x47, 0xbd, 0xf9, 0xc3, 0xd9, 0x1c,
	0x42, 0xee, 0xee, 0x67, 0x6b, 0xb4, 0x7c, 0xf7, 0xec, 0x5d, 0x67, 0x14, 0x27, 0x98, 0x7d, 0x1f,
	0x82, 0xf8, 0x19, 0x1c, 0xaf, 0x83, 0xbf, 0xa3, 0xdc, 0x36, 0x68, 0x67, 0x6c, 0xca, 0x04, 0xfb,
	0x17, 0x15, 0xe3, 0x17, 0xf0, 0x38, 0xe1, 0x92, 0x74, 0xe4, 0xcf, 0x7f, 0x57, 0xe0, 0x83, 0x98,
	0x3b, 0x20, 0x80, 0x82, 0xf9, 0xfd, 0x40, 0x37, 0x2f, 0xd4, 0x1d, 0x54, 0x82, 0xdd, 0xb6, 0xde,
	0x6a, 0xe9, 0xe7, 0x86, 0xaa, 0xa0, 0x7d, 0xd8, 0x6b, 0x0f, 0xda, 0x83, 0x97, 0x2d, 0x83, 0xa8,
	0x19, 0x74, 0x00, 0x25, 0xf3, 0xda, 0x30, 0xfa, 0xbd, 0x6e, 0x5f, 0xef, 0x77, 0xd5, 0xac, 0xff,
	0xdd, 0x72, 0x9d, 0xf3, 0xd7, 0x44, 0x3f, 0xeb, 0x98, 0x17, 0x6a, 0x1e, 0x15, 0x21, 0xdf, 0xbd,
	0xea, 0x74, 0xaf, 0xd4, 0x82, 0x1f, 0x6e, 0xeb, 0x84, 0x74, 0xfb, 0xea, 0x2e, 0x2a, 0x03, 0xb4,
	0x8c, 0xcb, 0xcb, 0x9e, 0xd1, 0xeb, 0x19, 0x44, 0xdd, 0xf3, 0xa1, 0xcc, 0x5e, 0xe7, 0x4a, 0x6f,
	0x5f, 0xa8, 0x45, 0x7f, 0x73, 0x69, 0xf4, 0xfb, 0x83, 0xb6, 0xa1, 0x42, 0xf3, 0x8f, 0x3c, 0x40,
	0x38, 0x32, 0xe8, 0x35, 0x1c, 0x49, 0x0f, 0x6a, 0xf1, 0xf9, 0x78, 0x22, 0x22, 0x07, 0x27, 0x91,
	0xe7, 0x49, 0x76, 0xb5, 0x0a, 0x4e, 0x4b, 0x59, 0x28, 0x85, 0x77, 0xd0, 0x4f, 0xf0, 0xa1, 0x3c,
	0x34, 0xf9, 0x74, 0xf4, 0x5f, 0xdc, 0x3f, 0x00, 0x75, 0xdd, 0xc1, 0x50, 0x25, 0x69, 0x0a, 0x16,
	0x8e, 0x57, 0xf9, 0x34, 0x7e, 0x6b, 0xa2, 0x83, 0xe0, 0x1d, 0xf4, 0x16, 0x2a, 0xdb, 0x9d, 0x06,
	0x7d, 0x11, 0xbf, 0x24, 0xdd, 0xcd, 0x2a, 0xf5, 0x07, 0x66, 0x07, 0xe0, 0xaf, 0xe0, 0x60, 0x6d,
	0x46, 0x63, 0x7a, 0x25, 0x7b, 0x4b, 0x4c, 0xaf, 0x2d, 0x23, 0x8e, 0x77, 0xd0, 0x35, 0x94, 0xe3,
	0xf3, 0x84, 0xa2, 0x16, 0x98, 0x38, 0xe7, 0x95, 0x93, 0x94, 0x8c, 0xe0, 0xe2, 0xd7, 0x70, 0xb8,
	0x31, 0x31, 0x28, 0xaa, 0xf6, 0xb6, 0xa1, 0xac, 0x3c, 0x4d, 0x4f, 0x5a, 0x21, 0xb4, 0x7e, 0x7c,
	0x75, 0x3d, 0xb6, 0xc4, 0x64, 0x7e, 0x73, 0x3a, 0xe4, 0xb3, 0x46, 0xf3, 0xd9, 0xf3, 0xaf, 0xea,
	0x33, 0xcb, 0xa5, 0xd6, 0x2d, 0xb3, 0x04, 0xb5, 0xea, 0xdc, 0x1d, 0x37, 0x08, 0xbd, 0x9d, 0x7b,
	0x74, 0xca, 0xea, 0xba, 0xcd, 0xc5, 0x84, 0xb9, 0x75, 0x93, 0xb9, 0x77, 0xcc, 0x6d, 0x58, 0xb6,
	0x60, 0xee, 0x1b, 0x3a, 0x64, 0x5e, 0xc3, 0x5b, 0x44, 0x5c, 0x67, 0xd8, 0x08, 0x60, 0x6f, 0x0a,
	0xf2, 0x97, 0xf3, 0xc5, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xa5, 0x8b, 0x16, 0x85, 0x0a,
	0x00, 0x00,
}
