// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vegetable.proto

package vegetable // import "github.com/2018-miraikeitai-org/Rakusale-Another-Server/interfaces/server/rpc/vegetable"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vegetable struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fee                  int64    `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	IsChemical           bool     `protobuf:"varint,3,opt,name=is_chemical,json=isChemical,proto3" json:"is_chemical,omitempty"`
	ImagePath            string   `protobuf:"bytes,4,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	ProductionDate       string   `protobuf:"bytes,5,opt,name=production_date,json=productionDate,proto3" json:"production_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vegetable) Reset()         { *m = Vegetable{} }
func (m *Vegetable) String() string { return proto.CompactTextString(m) }
func (*Vegetable) ProtoMessage()    {}
func (*Vegetable) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_dba829073066b2a9, []int{0}
}
func (m *Vegetable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vegetable.Unmarshal(m, b)
}
func (m *Vegetable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vegetable.Marshal(b, m, deterministic)
}
func (dst *Vegetable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vegetable.Merge(dst, src)
}
func (m *Vegetable) XXX_Size() int {
	return xxx_messageInfo_Vegetable.Size(m)
}
func (m *Vegetable) XXX_DiscardUnknown() {
	xxx_messageInfo_Vegetable.DiscardUnknown(m)
}

var xxx_messageInfo_Vegetable proto.InternalMessageInfo

func (m *Vegetable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vegetable) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Vegetable) GetIsChemical() bool {
	if m != nil {
		return m.IsChemical
	}
	return false
}

func (m *Vegetable) GetImagePath() string {
	if m != nil {
		return m.ImagePath
	}
	return ""
}

func (m *Vegetable) GetProductionDate() string {
	if m != nil {
		return m.ProductionDate
	}
	return ""
}

// Get
type GetMyVegetablesRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMyVegetablesRequest) Reset()         { *m = GetMyVegetablesRequest{} }
func (m *GetMyVegetablesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMyVegetablesRequest) ProtoMessage()    {}
func (*GetMyVegetablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_dba829073066b2a9, []int{1}
}
func (m *GetMyVegetablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyVegetablesRequest.Unmarshal(m, b)
}
func (m *GetMyVegetablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyVegetablesRequest.Marshal(b, m, deterministic)
}
func (dst *GetMyVegetablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyVegetablesRequest.Merge(dst, src)
}
func (m *GetMyVegetablesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMyVegetablesRequest.Size(m)
}
func (m *GetMyVegetablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyVegetablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyVegetablesRequest proto.InternalMessageInfo

func (m *GetMyVegetablesRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetMyVegetablesResponse struct {
	Status               int64        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Vegetables           []*Vegetable `protobuf:"bytes,2,rep,name=vegetables,proto3" json:"vegetables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetMyVegetablesResponse) Reset()         { *m = GetMyVegetablesResponse{} }
func (m *GetMyVegetablesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMyVegetablesResponse) ProtoMessage()    {}
func (*GetMyVegetablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_dba829073066b2a9, []int{2}
}
func (m *GetMyVegetablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyVegetablesResponse.Unmarshal(m, b)
}
func (m *GetMyVegetablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyVegetablesResponse.Marshal(b, m, deterministic)
}
func (dst *GetMyVegetablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyVegetablesResponse.Merge(dst, src)
}
func (m *GetMyVegetablesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMyVegetablesResponse.Size(m)
}
func (m *GetMyVegetablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyVegetablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyVegetablesResponse proto.InternalMessageInfo

func (m *GetMyVegetablesResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetMyVegetablesResponse) GetVegetables() []*Vegetable {
	if m != nil {
		return m.Vegetables
	}
	return nil
}

type VegetablesEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VegetablesEmpty) Reset()         { *m = VegetablesEmpty{} }
func (m *VegetablesEmpty) String() string { return proto.CompactTextString(m) }
func (*VegetablesEmpty) ProtoMessage()    {}
func (*VegetablesEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_dba829073066b2a9, []int{3}
}
func (m *VegetablesEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VegetablesEmpty.Unmarshal(m, b)
}
func (m *VegetablesEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VegetablesEmpty.Marshal(b, m, deterministic)
}
func (dst *VegetablesEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VegetablesEmpty.Merge(dst, src)
}
func (m *VegetablesEmpty) XXX_Size() int {
	return xxx_messageInfo_VegetablesEmpty.Size(m)
}
func (m *VegetablesEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_VegetablesEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_VegetablesEmpty proto.InternalMessageInfo

type GetAllVegetablesResponse struct {
	Vegetables           []*Vegetable `protobuf:"bytes,1,rep,name=vegetables,proto3" json:"vegetables,omitempty"`
	Status               int64        `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetAllVegetablesResponse) Reset()         { *m = GetAllVegetablesResponse{} }
func (m *GetAllVegetablesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllVegetablesResponse) ProtoMessage()    {}
func (*GetAllVegetablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_dba829073066b2a9, []int{4}
}
func (m *GetAllVegetablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllVegetablesResponse.Unmarshal(m, b)
}
func (m *GetAllVegetablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllVegetablesResponse.Marshal(b, m, deterministic)
}
func (dst *GetAllVegetablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllVegetablesResponse.Merge(dst, src)
}
func (m *GetAllVegetablesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllVegetablesResponse.Size(m)
}
func (m *GetAllVegetablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllVegetablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllVegetablesResponse proto.InternalMessageInfo

func (m *GetAllVegetablesResponse) GetVegetables() []*Vegetable {
	if m != nil {
		return m.Vegetables
	}
	return nil
}

func (m *GetAllVegetablesResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

// Create
type VegetableImage struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VegetableImage) Reset()         { *m = VegetableImage{} }
func (m *VegetableImage) String() string { return proto.CompactTextString(m) }
func (*VegetableImage) ProtoMessage()    {}
func (*VegetableImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_dba829073066b2a9, []int{5}
}
func (m *VegetableImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VegetableImage.Unmarshal(m, b)
}
func (m *VegetableImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VegetableImage.Marshal(b, m, deterministic)
}
func (dst *VegetableImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VegetableImage.Merge(dst, src)
}
func (m *VegetableImage) XXX_Size() int {
	return xxx_messageInfo_VegetableImage.Size(m)
}
func (m *VegetableImage) XXX_DiscardUnknown() {
	xxx_messageInfo_VegetableImage.DiscardUnknown(m)
}

var xxx_messageInfo_VegetableImage proto.InternalMessageInfo

func (m *VegetableImage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PostMyVegetableRequest struct {
	Token                string          `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Vegetable            *Vegetable      `protobuf:"bytes,2,opt,name=vegetable,proto3" json:"vegetable,omitempty"`
	Image                *VegetableImage `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PostMyVegetableRequest) Reset()         { *m = PostMyVegetableRequest{} }
func (m *PostMyVegetableRequest) String() string { return proto.CompactTextString(m) }
func (*PostMyVegetableRequest) ProtoMessage()    {}
func (*PostMyVegetableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_dba829073066b2a9, []int{6}
}
func (m *PostMyVegetableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMyVegetableRequest.Unmarshal(m, b)
}
func (m *PostMyVegetableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMyVegetableRequest.Marshal(b, m, deterministic)
}
func (dst *PostMyVegetableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMyVegetableRequest.Merge(dst, src)
}
func (m *PostMyVegetableRequest) XXX_Size() int {
	return xxx_messageInfo_PostMyVegetableRequest.Size(m)
}
func (m *PostMyVegetableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMyVegetableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostMyVegetableRequest proto.InternalMessageInfo

func (m *PostMyVegetableRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PostMyVegetableRequest) GetVegetable() *Vegetable {
	if m != nil {
		return m.Vegetable
	}
	return nil
}

func (m *PostMyVegetableRequest) GetImage() *VegetableImage {
	if m != nil {
		return m.Image
	}
	return nil
}

type PostMyVegetableResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostMyVegetableResponse) Reset()         { *m = PostMyVegetableResponse{} }
func (m *PostMyVegetableResponse) String() string { return proto.CompactTextString(m) }
func (*PostMyVegetableResponse) ProtoMessage()    {}
func (*PostMyVegetableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_dba829073066b2a9, []int{7}
}
func (m *PostMyVegetableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMyVegetableResponse.Unmarshal(m, b)
}
func (m *PostMyVegetableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMyVegetableResponse.Marshal(b, m, deterministic)
}
func (dst *PostMyVegetableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMyVegetableResponse.Merge(dst, src)
}
func (m *PostMyVegetableResponse) XXX_Size() int {
	return xxx_messageInfo_PostMyVegetableResponse.Size(m)
}
func (m *PostMyVegetableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMyVegetableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostMyVegetableResponse proto.InternalMessageInfo

func (m *PostMyVegetableResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

// Update
type PutMyVegetableRequest struct {
	Token                string     `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	VId                  int64      `protobuf:"varint,2,opt,name=v_id,json=vId,proto3" json:"v_id,omitempty"`
	Vegetable            *Vegetable `protobuf:"bytes,3,opt,name=vegetable,proto3" json:"vegetable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutMyVegetableRequest) Reset()         { *m = PutMyVegetableRequest{} }
func (m *PutMyVegetableRequest) String() string { return proto.CompactTextString(m) }
func (*PutMyVegetableRequest) ProtoMessage()    {}
func (*PutMyVegetableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_dba829073066b2a9, []int{8}
}
func (m *PutMyVegetableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMyVegetableRequest.Unmarshal(m, b)
}
func (m *PutMyVegetableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMyVegetableRequest.Marshal(b, m, deterministic)
}
func (dst *PutMyVegetableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMyVegetableRequest.Merge(dst, src)
}
func (m *PutMyVegetableRequest) XXX_Size() int {
	return xxx_messageInfo_PutMyVegetableRequest.Size(m)
}
func (m *PutMyVegetableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMyVegetableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutMyVegetableRequest proto.InternalMessageInfo

func (m *PutMyVegetableRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PutMyVegetableRequest) GetVId() int64 {
	if m != nil {
		return m.VId
	}
	return 0
}

func (m *PutMyVegetableRequest) GetVegetable() *Vegetable {
	if m != nil {
		return m.Vegetable
	}
	return nil
}

type PutMyVegetableResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutMyVegetableResponse) Reset()         { *m = PutMyVegetableResponse{} }
func (m *PutMyVegetableResponse) String() string { return proto.CompactTextString(m) }
func (*PutMyVegetableResponse) ProtoMessage()    {}
func (*PutMyVegetableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_dba829073066b2a9, []int{9}
}
func (m *PutMyVegetableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMyVegetableResponse.Unmarshal(m, b)
}
func (m *PutMyVegetableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMyVegetableResponse.Marshal(b, m, deterministic)
}
func (dst *PutMyVegetableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMyVegetableResponse.Merge(dst, src)
}
func (m *PutMyVegetableResponse) XXX_Size() int {
	return xxx_messageInfo_PutMyVegetableResponse.Size(m)
}
func (m *PutMyVegetableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMyVegetableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutMyVegetableResponse proto.InternalMessageInfo

func (m *PutMyVegetableResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

// Delete
type DeleteMyVegetableRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	VId                  int64    `protobuf:"varint,2,opt,name=v_id,json=vId,proto3" json:"v_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMyVegetableRequest) Reset()         { *m = DeleteMyVegetableRequest{} }
func (m *DeleteMyVegetableRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMyVegetableRequest) ProtoMessage()    {}
func (*DeleteMyVegetableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_dba829073066b2a9, []int{10}
}
func (m *DeleteMyVegetableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMyVegetableRequest.Unmarshal(m, b)
}
func (m *DeleteMyVegetableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMyVegetableRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteMyVegetableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMyVegetableRequest.Merge(dst, src)
}
func (m *DeleteMyVegetableRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMyVegetableRequest.Size(m)
}
func (m *DeleteMyVegetableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMyVegetableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMyVegetableRequest proto.InternalMessageInfo

func (m *DeleteMyVegetableRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeleteMyVegetableRequest) GetVId() int64 {
	if m != nil {
		return m.VId
	}
	return 0
}

type DeleteMyVegetableResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMyVegetableResponse) Reset()         { *m = DeleteMyVegetableResponse{} }
func (m *DeleteMyVegetableResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMyVegetableResponse) ProtoMessage()    {}
func (*DeleteMyVegetableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vegetable_dba829073066b2a9, []int{11}
}
func (m *DeleteMyVegetableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMyVegetableResponse.Unmarshal(m, b)
}
func (m *DeleteMyVegetableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMyVegetableResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteMyVegetableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMyVegetableResponse.Merge(dst, src)
}
func (m *DeleteMyVegetableResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMyVegetableResponse.Size(m)
}
func (m *DeleteMyVegetableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMyVegetableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMyVegetableResponse proto.InternalMessageInfo

func (m *DeleteMyVegetableResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*Vegetable)(nil), "vegetable.Vegetable")
	proto.RegisterType((*GetMyVegetablesRequest)(nil), "vegetable.GetMyVegetablesRequest")
	proto.RegisterType((*GetMyVegetablesResponse)(nil), "vegetable.GetMyVegetablesResponse")
	proto.RegisterType((*VegetablesEmpty)(nil), "vegetable.VegetablesEmpty")
	proto.RegisterType((*GetAllVegetablesResponse)(nil), "vegetable.GetAllVegetablesResponse")
	proto.RegisterType((*VegetableImage)(nil), "vegetable.VegetableImage")
	proto.RegisterType((*PostMyVegetableRequest)(nil), "vegetable.PostMyVegetableRequest")
	proto.RegisterType((*PostMyVegetableResponse)(nil), "vegetable.PostMyVegetableResponse")
	proto.RegisterType((*PutMyVegetableRequest)(nil), "vegetable.PutMyVegetableRequest")
	proto.RegisterType((*PutMyVegetableResponse)(nil), "vegetable.PutMyVegetableResponse")
	proto.RegisterType((*DeleteMyVegetableRequest)(nil), "vegetable.DeleteMyVegetableRequest")
	proto.RegisterType((*DeleteMyVegetableResponse)(nil), "vegetable.DeleteMyVegetableResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VegetablesClient is the client API for Vegetables service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VegetablesClient interface {
	GetMyBoughtVegetables(ctx context.Context, in *GetMyVegetablesRequest, opts ...grpc.CallOption) (*GetMyVegetablesResponse, error)
	GetMySoldVegetables(ctx context.Context, in *GetMyVegetablesRequest, opts ...grpc.CallOption) (*GetMyVegetablesResponse, error)
	GetAllVegetables(ctx context.Context, in *VegetablesEmpty, opts ...grpc.CallOption) (*GetAllVegetablesResponse, error)
	PostMyVegetable(ctx context.Context, in *PostMyVegetableRequest, opts ...grpc.CallOption) (*PostMyVegetableResponse, error)
	PutMyVegetable(ctx context.Context, in *PutMyVegetableRequest, opts ...grpc.CallOption) (*PutMyVegetableResponse, error)
	DeleteMyVegetable(ctx context.Context, in *DeleteMyVegetableRequest, opts ...grpc.CallOption) (*DeleteMyVegetableResponse, error)
}

type vegetablesClient struct {
	cc *grpc.ClientConn
}

func NewVegetablesClient(cc *grpc.ClientConn) VegetablesClient {
	return &vegetablesClient{cc}
}

func (c *vegetablesClient) GetMyBoughtVegetables(ctx context.Context, in *GetMyVegetablesRequest, opts ...grpc.CallOption) (*GetMyVegetablesResponse, error) {
	out := new(GetMyVegetablesResponse)
	err := c.cc.Invoke(ctx, "/vegetable.Vegetables/GetMyBoughtVegetables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vegetablesClient) GetMySoldVegetables(ctx context.Context, in *GetMyVegetablesRequest, opts ...grpc.CallOption) (*GetMyVegetablesResponse, error) {
	out := new(GetMyVegetablesResponse)
	err := c.cc.Invoke(ctx, "/vegetable.Vegetables/GetMySoldVegetables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vegetablesClient) GetAllVegetables(ctx context.Context, in *VegetablesEmpty, opts ...grpc.CallOption) (*GetAllVegetablesResponse, error) {
	out := new(GetAllVegetablesResponse)
	err := c.cc.Invoke(ctx, "/vegetable.Vegetables/GetAllVegetables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vegetablesClient) PostMyVegetable(ctx context.Context, in *PostMyVegetableRequest, opts ...grpc.CallOption) (*PostMyVegetableResponse, error) {
	out := new(PostMyVegetableResponse)
	err := c.cc.Invoke(ctx, "/vegetable.Vegetables/PostMyVegetable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vegetablesClient) PutMyVegetable(ctx context.Context, in *PutMyVegetableRequest, opts ...grpc.CallOption) (*PutMyVegetableResponse, error) {
	out := new(PutMyVegetableResponse)
	err := c.cc.Invoke(ctx, "/vegetable.Vegetables/PutMyVegetable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vegetablesClient) DeleteMyVegetable(ctx context.Context, in *DeleteMyVegetableRequest, opts ...grpc.CallOption) (*DeleteMyVegetableResponse, error) {
	out := new(DeleteMyVegetableResponse)
	err := c.cc.Invoke(ctx, "/vegetable.Vegetables/DeleteMyVegetable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VegetablesServer is the server API for Vegetables service.
type VegetablesServer interface {
	GetMyBoughtVegetables(context.Context, *GetMyVegetablesRequest) (*GetMyVegetablesResponse, error)
	GetMySoldVegetables(context.Context, *GetMyVegetablesRequest) (*GetMyVegetablesResponse, error)
	GetAllVegetables(context.Context, *VegetablesEmpty) (*GetAllVegetablesResponse, error)
	PostMyVegetable(context.Context, *PostMyVegetableRequest) (*PostMyVegetableResponse, error)
	PutMyVegetable(context.Context, *PutMyVegetableRequest) (*PutMyVegetableResponse, error)
	DeleteMyVegetable(context.Context, *DeleteMyVegetableRequest) (*DeleteMyVegetableResponse, error)
}

func RegisterVegetablesServer(s *grpc.Server, srv VegetablesServer) {
	s.RegisterService(&_Vegetables_serviceDesc, srv)
}

func _Vegetables_GetMyBoughtVegetables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyVegetablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VegetablesServer).GetMyBoughtVegetables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vegetable.Vegetables/GetMyBoughtVegetables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VegetablesServer).GetMyBoughtVegetables(ctx, req.(*GetMyVegetablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vegetables_GetMySoldVegetables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyVegetablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VegetablesServer).GetMySoldVegetables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vegetable.Vegetables/GetMySoldVegetables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VegetablesServer).GetMySoldVegetables(ctx, req.(*GetMyVegetablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vegetables_GetAllVegetables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VegetablesEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VegetablesServer).GetAllVegetables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vegetable.Vegetables/GetAllVegetables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VegetablesServer).GetAllVegetables(ctx, req.(*VegetablesEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vegetables_PostMyVegetable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMyVegetableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VegetablesServer).PostMyVegetable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vegetable.Vegetables/PostMyVegetable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VegetablesServer).PostMyVegetable(ctx, req.(*PostMyVegetableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vegetables_PutMyVegetable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutMyVegetableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VegetablesServer).PutMyVegetable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vegetable.Vegetables/PutMyVegetable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VegetablesServer).PutMyVegetable(ctx, req.(*PutMyVegetableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vegetables_DeleteMyVegetable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMyVegetableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VegetablesServer).DeleteMyVegetable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vegetable.Vegetables/DeleteMyVegetable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VegetablesServer).DeleteMyVegetable(ctx, req.(*DeleteMyVegetableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Vegetables_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vegetable.Vegetables",
	HandlerType: (*VegetablesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyBoughtVegetables",
			Handler:    _Vegetables_GetMyBoughtVegetables_Handler,
		},
		{
			MethodName: "GetMySoldVegetables",
			Handler:    _Vegetables_GetMySoldVegetables_Handler,
		},
		{
			MethodName: "GetAllVegetables",
			Handler:    _Vegetables_GetAllVegetables_Handler,
		},
		{
			MethodName: "PostMyVegetable",
			Handler:    _Vegetables_PostMyVegetable_Handler,
		},
		{
			MethodName: "PutMyVegetable",
			Handler:    _Vegetables_PutMyVegetable_Handler,
		},
		{
			MethodName: "DeleteMyVegetable",
			Handler:    _Vegetables_DeleteMyVegetable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vegetable.proto",
}

func init() { proto.RegisterFile("vegetable.proto", fileDescriptor_vegetable_dba829073066b2a9) }

var fileDescriptor_vegetable_dba829073066b2a9 = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4f, 0x4f, 0xdb, 0x4e,
	0x10, 0xc5, 0x38, 0xa0, 0x5f, 0x86, 0x9f, 0x08, 0x6c, 0x21, 0x98, 0x48, 0x55, 0xc3, 0x16, 0xa9,
	0xb9, 0x24, 0x86, 0xd0, 0x43, 0xaf, 0xfc, 0xa9, 0x10, 0x87, 0x4a, 0xc8, 0xa8, 0x45, 0xe5, 0xd0,
	0xb0, 0xd8, 0x83, 0xbd, 0xc2, 0xf6, 0xba, 0xde, 0x75, 0x24, 0x3e, 0x47, 0x6f, 0xfd, 0x2c, 0xfd,
	0x70, 0x15, 0x1b, 0xf0, 0x1f, 0x30, 0x2e, 0x52, 0xd5, 0xdb, 0xee, 0xf8, 0xed, 0xbc, 0x37, 0x33,
	0x6f, 0x64, 0xe8, 0x4c, 0xd1, 0x47, 0xc5, 0xae, 0x42, 0x1c, 0x25, 0xa9, 0x50, 0x82, 0xb4, 0xf3,
	0x00, 0xfd, 0x69, 0x40, 0xfb, 0xcb, 0xc3, 0x8d, 0x10, 0x68, 0xc5, 0x2c, 0x42, 0xcb, 0xe8, 0x1b,
	0x83, 0xb6, 0xa3, 0xcf, 0x64, 0x05, 0xcc, 0x6b, 0x44, 0x6b, 0xbe, 0x6f, 0x0c, 0x4c, 0xe7, 0xee,
	0x48, 0xde, 0xc0, 0x12, 0x97, 0x13, 0x37, 0xc0, 0x88, 0xbb, 0x2c, 0xb4, 0xcc, 0xbe, 0x31, 0xf8,
	0xcf, 0x01, 0x2e, 0x0f, 0xef, 0x23, 0xe4, 0x35, 0x00, 0x8f, 0x98, 0x8f, 0x93, 0x84, 0xa9, 0xc0,
	0x6a, 0xe9, 0x64, 0x6d, 0x1d, 0x39, 0x65, 0x2a, 0x20, 0xef, 0xa0, 0x93, 0xa4, 0xc2, 0xcb, 0x5c,
	0xc5, 0x45, 0x3c, 0xf1, 0x98, 0x42, 0x6b, 0x41, 0x63, 0x96, 0x8b, 0xf0, 0x11, 0x53, 0x48, 0x47,
	0xd0, 0x3d, 0x46, 0xf5, 0xe9, 0x36, 0x17, 0x28, 0x1d, 0xfc, 0x9e, 0xa1, 0x54, 0x64, 0x0d, 0x16,
	0x94, 0xb8, 0xc1, 0xf8, 0x5e, 0xe9, 0xec, 0x42, 0x7d, 0xd8, 0x78, 0x82, 0x97, 0x89, 0x88, 0x25,
	0x92, 0x2e, 0x2c, 0x4a, 0xc5, 0x54, 0x26, 0xf5, 0x0b, 0xd3, 0xb9, 0xbf, 0x91, 0xf7, 0x00, 0x79,
	0x33, 0xa4, 0x35, 0xdf, 0x37, 0x07, 0x4b, 0xe3, 0xb5, 0x51, 0xd1, 0xb0, 0x3c, 0x95, 0x53, 0xc2,
	0xd1, 0x55, 0xe8, 0x14, 0x1c, 0x1f, 0xa3, 0x44, 0xdd, 0xd2, 0x00, 0xac, 0x63, 0x54, 0xfb, 0x61,
	0x58, 0x43, 0x5e, 0x25, 0x31, 0x5e, 0x46, 0x52, 0x92, 0x3c, 0x5f, 0x96, 0x4c, 0xb7, 0x61, 0x39,
	0x7f, 0x70, 0x72, 0xd7, 0xd4, 0xbb, 0xb1, 0x79, 0x4c, 0x31, 0x5d, 0xda, 0xff, 0x8e, 0x3e, 0xd3,
	0x1f, 0x06, 0x74, 0x4f, 0x85, 0x2c, 0x77, 0xa3, 0xb1, 0x79, 0x64, 0x0c, 0x85, 0x2d, 0x34, 0xe3,
	0x73, 0x1a, 0x0b, 0x18, 0xb1, 0x61, 0x41, 0x8f, 0x55, 0x7b, 0x60, 0x69, 0xbc, 0x59, 0x87, 0xd7,
	0x12, 0x9d, 0x19, 0x8e, 0xee, 0xc2, 0xc6, 0x13, 0x51, 0xcd, 0x13, 0xa2, 0x0a, 0xd6, 0x4f, 0xb3,
	0x97, 0x97, 0xb1, 0x0a, 0xad, 0xe9, 0x84, 0x7b, 0x0f, 0x7e, 0x9d, 0x9e, 0x78, 0xd5, 0xca, 0xcc,
	0x17, 0x55, 0x46, 0x77, 0xa0, 0xfb, 0x98, 0xf5, 0x0f, 0x3a, 0x0f, 0xc1, 0x3a, 0xc2, 0x10, 0x15,
	0xfe, 0x85, 0x54, 0xba, 0x07, 0x9b, 0x35, 0x49, 0x9a, 0x99, 0xc7, 0xbf, 0x5a, 0x00, 0x85, 0xeb,
	0xc8, 0x25, 0xac, 0xeb, 0x2d, 0x38, 0x10, 0x99, 0x1f, 0xa8, 0xd2, 0x87, 0xad, 0x52, 0xd1, 0xf5,
	0x7b, 0xd5, 0xa3, 0x4d, 0x90, 0x99, 0x0c, 0x3a, 0x47, 0xbe, 0xc1, 0x2b, 0xfd, 0xf1, 0x4c, 0x84,
	0xde, 0xbf, 0xc8, 0xff, 0x19, 0x56, 0x1e, 0xef, 0x12, 0xe9, 0xd5, 0x4d, 0x6c, 0xb6, 0x7b, 0xbd,
	0xb7, 0xd5, 0xac, 0xb5, 0x4b, 0x48, 0xe7, 0xc8, 0x05, 0x74, 0x1e, 0x99, 0xaf, 0x22, 0xb9, 0x7e,
	0x5b, 0x2a, 0x92, 0x9f, 0xf1, 0x2e, 0x9d, 0x23, 0xe7, 0xb0, 0x5c, 0xf5, 0x0b, 0xe9, 0x97, 0xdf,
	0xd5, 0x19, 0xb8, 0xb7, 0xd5, 0x80, 0xc8, 0x13, 0x5f, 0xc2, 0xea, 0x13, 0x47, 0x90, 0x72, 0xc1,
	0xcf, 0x99, 0xae, 0xb7, 0xdd, 0x0c, 0x7a, 0x60, 0x38, 0xf8, 0x7a, 0x71, 0xee, 0x73, 0x15, 0x64,
	0x57, 0x23, 0x57, 0x44, 0xf6, 0x78, 0x67, 0xf7, 0xc3, 0x30, 0xe2, 0x29, 0xe3, 0x37, 0xc8, 0x15,
	0xe3, 0x43, 0x91, 0xfa, 0xb6, 0xc3, 0x6e, 0x32, 0xc9, 0x42, 0x1c, 0xee, 0xc7, 0x42, 0x05, 0x98,
	0x0e, 0xcf, 0x30, 0x9d, 0x62, 0x6a, 0xf3, 0x58, 0x61, 0x7a, 0xcd, 0x5c, 0x94, 0xb6, 0x9c, 0x45,
	0xd2, 0xc4, 0xb5, 0x73, 0xda, 0xab, 0x45, 0xfd, 0xbf, 0xd9, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0x1f, 0xd7, 0x15, 0x37, 0x82, 0x06, 0x00, 0x00,
}
